### ISSUE TITLE
No way to add a subscription to a Management Group

### ISSUE THREAD

**Issue by sebastus** [pulumi/pulumi-azure-nextgen#101]
This page details how to do it - but there's no subscription Id parameter anywhere.

https://www.pulumi.com/docs/reference/pkg/azure-nextgen/management/managementgroupsubscription/

If you execute the api as documented, "pulumi up" complains because there's no subscription id.

error: cannot check existence of resource /providers/Microsoft.Management/managementGroups/golive/subscriptions/{subscriptionId}: status code 400

Using azure-nextgen-csharp latest.

**Comment by mikhailshilkov** [comment]
The `subscriptionId` parameter will be added in 0.4.0
