### ISSUE TITLE
Side by side providers doesn't seem to work to list resources

### ISSUE THREAD

**Issue by PawelStadnicki** [pulumi/pulumi-azure-nextgen#105]
I experimented with both azure providers a the same time to provision resources and it isfine.
But when I want to list any resource I'm getting errors like azure:keyvault/getKeyVault:getKeyVault not found or something similar to "function data dosn't exists" (happened several times but not now hence don't remember exact message).

It is the same whenever I start the azure-csharp project first or azure-nextgen-csharp. It doesn't matter what resource I want to list.

Something specific to setup to make it work or it is not supported?

**Comment by mikhailshilkov** [comment]
That's odd because the result of `getXyz` should not depend on how it was provisioned, even if that was done via the Azure portal. Any repro program that you can share?

**Comment by PawelStadnicki** [comment]
It happens for every resource created with this pattern:
- list some resource with nextgen provider
- list resource with plain provider

I think that the problem may be in proj/pulumi configuration.

It is azure-nextgen-csharp project.
Then I added Pulumi.Azure via nuget manager.
Maybe some plugin must be installed manually as well but when I list the plugins both are available.

I also use same subscription manager in both cases which may be also worth notice:
`public static InvokeOptions Create(string subscriptionId) =>
            new InvokeOptions
            {
                Provider = new Provider(subscriptionId,
                    new ProviderArgs
                    {
                        SubscriptionId = subscriptionId
                    }
                )
            };`

**Comment by mikhailshilkov** [comment]
The setup sounds fine, there shouldn't be any special steps required. I'd still love to get a repro program and the exact error message that you are hitting.

**Comment by PawelStadnicki** [comment]
For now I can give you exact message, hope it will help.

`One or more errors occurred. (Status(StatusCode="Unknown", Detail="invocation of azure:appservice/getFunctionApp:getFunctionApp returned an error: Resource type azure:appservice/getFunctionApp:getFunctionApp not found", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1606334744.431000000","description":"Error received from peer ipv4:127.0.0.1:58860","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\surface\call.cc","file_line":1062,"grpc_message":"invocation of azure:appservice/getFunctionApp:getFunctionApp returned an error: Resource type azure:appservice/getFunctionApp:getFunctionApp not found","grpc_status":2}"))`

version.txt: 
```
azure-nextgen
0.2.8
```
Ok: AppFunction API differs between Pulumi.Azure and Pulumi.AzureNextGen.

But the same problem is with every other resource.
I get it when I change the Azure provider, example for keyvault, sample code that breaks althought for nextgen it is fine (with small api name adjustment):

```
public GetKeyVaultResult GetVaultResult(string resourceGroup, string vault)
        {
            return GetKeyVault.InvokeAsync(new GetKeyVaultArgs()
            {
                ResourceGroupName = resourceGroup,
                //VaultName = vault
                Name = vault
            }, GetProvider(resourceGroup)).Result;
        }
```

Result:

`One or more errors occurred. (Status(StatusCode="Unknown", Detail="invocation of azure:keyvault/getKeyVault:getKeyVault returned an error: Resource type azure:keyvault/getKeyVault:getKeyVault not found", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1606335381.086000000","description":"Error received from peer ipv4:127.0.0.1:59159","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\surface\call.cc","file_line":1062,"grpc_message":"invocation of azure:keyvault/getKeyVault:getKeyVault returned an error: Resource type azure:keyvault/getKeyVault:getKeyVault not found","grpc_status":2}"))`

**Comment by mikhailshilkov** [comment]
Are you trying to mix a resource from one provider (`azure`) with a `provider` option from another provider (`azure-nextgen`)? What exactly does `GetProvider` do?

**Comment by PawelStadnicki** [comment]
it translates resource name to subscription and returns invoke options:

```
new InvokeOptions {
                Provider = new Provider(subscriptionId,
                    new ProviderArgs
                    {
                        SubscriptionId = subscriptionId
                    }
                )
            };  
```

**Comment by mikhailshilkov** [comment]
Is `Provider` from the same assembly as `GetKeyVault`?

**Comment by PawelStadnicki** [comment]
No because I thought that this type is from Pulumi namespace only
 -> Большое спасибо 👍
