### ISSUE TITLE
getResourceUploadUrl is missed in provider

### ISSUE THREAD

**Issue by metacpp** [pulumi/pulumi-azure-nextgen#11]
Hello there,

I am using pulumi's nextgen provider to provision service and deploy app. During the experimentation, I found an issue in `appplatform` resource. In the swagger, you can see there's a `getResourceUploadUrl` under each app of `appplatform` resource:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/appplatform/resource-manager/Microsoft.AppPlatform/preview/2019-05-01-preview/appplatform.json#L662

But, this operation is not generated in the provider:
https://www.pulumi.com/docs/reference/pkg/azure-nextgen/appplatform/app/

Can you take a look at it ?

**Comment by mikhailshilkov** [comment]
@metacpp Thank you for giving it a try! I'm sorry we missed an important endpoint.

Indeed, right now we generate a limited set of invokes. I believe the rule right now is that only `list*` POST requests are generated. We'll take a look at extending those to `get*` POSTs too.

**Comment by metacpp** [comment]
> @metacpp Thank you for giving it a try! I'm sorry we missed an important endpoint.
> 
> Indeed, right now we generate a limited set of invokes. I believe the rule right now is that only `list*` POST requests are generated. We'll take a look at extending those to `get*` POSTs too.

Thanks for the quick response. This pattern is pretty common in many Azure resources. Once you get it works, feel free to let me now, I am willing to have a try. :-)

**Comment by mikhailshilkov** [comment]
This has been added to the dev build (e.g. here is the [node version](https://github.com/pulumi/pulumi-azure-nextgen/blob/master/sdk/nodejs/appplatform/latest/getAppResourceUploadUrl.ts)) and will be published in the next release. Docs will be updated at the time of the release.

**Comment by metacpp** [comment]
> This has been added to the dev build (e.g. here is the [node version](https://github.com/pulumi/pulumi-azure-nextgen/blob/master/sdk/nodejs/appplatform/latest/getAppResourceUploadUrl.ts)) and will be published in the next release. Docs will be updated at the time of the release.

Thanks for the quick turn-around ! When will C# version get updated ?

**Comment by mikhailshilkov** [comment]
You should be able to use the latest prerelease https://www.nuget.org/packages/Pulumi.AzureNextGen/0.1.1-alpha.1600879923
Otherwise, the next release (0.2.0) will probably come next week.
