### ISSUE TITLE
No straightforward method of replacing `latest` with fixed, stable versions

### ISSUE THREAD

**Issue by MerelyAPseudonym** [pulumi/pulumi-azure-nextgen#114]
At the moment, replacing `latest` with the (presumably equivalent) most-recent stable version for any particular resource requires trial-and-error inspections of the different versions. For example, consider the process of taking code that uses `azng.authorization.latest.RoleAssignment` and "pinning" it to the equivalent stable version. The most-recent stable release of the `authorization` module is [`v20200301`](https://github.com/pulumi/pulumi-azure-nextgen/tree/v0.2.4/sdk/nodejs/authorization/v20200301)—but that module version does not include `RoleAssignment`. Neither does [`v20190901 `](https://github.com/pulumi/pulumi-azure-nextgen/tree/v0.2.4/sdk/nodejs/authorization/v20190901), nor [`v20190601`](https://github.com/pulumi/pulumi-azure-nextgen/tree/v0.2.4/sdk/nodejs/authorization/v20190601), nor [`v20190101`](https://github.com/pulumi/pulumi-azure-nextgen/tree/v0.2.4/sdk/nodejs/authorization/v20190101)… (etc.) The most-recent stable release of the `authorization` module **that includes `RoleAssignment`** is actually [`v20150701`](https://github.com/pulumi/pulumi-azure-nextgen/tree/v0.2.4/sdk/nodejs/authorization/v20150701).

Ideally, this process of searching through module versions could be streamlined, automated, or eliminated.

**Comment by MisinformedDNA** [comment]
What if were to redefine `.Latest` as the latest stable version and then create `.LastestPreview` for the latest preview version?

**Comment by mikhailshilkov** [comment]
> What if were to redefine .Latest as the latest stable version and then create .LastestPreview for the latest preview version?

That's possible. I think this doesn't quite solve the original issue of how to pin `latest` to a specific version easily. Would you mind filing a new issue?

**Comment by MisinformedDNA** [comment]
I think I understand now. 

Would adding class comments on the (`Latest`) classes that say "This class currently reflects the API version '2015-07-01'." work?

**Comment by mikhailshilkov** [comment]
> Would adding class comments on the (Latest) classes that say "This class currently reflects the API version '2015-07-01'." work?

Yes, my current thinking is along these lines.

I wouldn't deprecate old versions - there may be legit reasons to use them. Also, we want to encourage folks to "pin" to a specific stable version before going to production and not force them out of that pinned version unless they need features from later ones.

**Comment by mikhailshilkov** [comment]
As a little help, you can now see what the latest version refers to in the docs, e.g. in https://www.pulumi.com/docs/reference/pkg/azure-nextgen/authorization/roledefinition/

![image](https://user-images.githubusercontent.com/1454008/102912620-eb0c8880-447d-11eb-8741-2a86c06628dd.png)

The same information is available in the resource tooltip in your IDE.
