### ISSUE TITLE
Storage Blob resource

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure-nextgen#13]
Currently, Blobs are not part of the ARM API surface, they are considered to be a part of the data plane.

However, it's desirable to have a blob as a resource: upload files to static websites, app service / function app deployments, callback functions.

**Comment by remojansen** [comment]
Hi @mikhailshilkov Is there a way to use the [`AccountStaticWebsite`](https://www.pulumi.com/docs/reference/pkg/azure/storage/account/#accountstaticwebsite)settings from the Azure Provider in the Azure NextGen provider?

**Comment by mikhailshilkov** [comment]
@remojansen Not at the moment. That operation is considered by Azure to belong to the data plane, so it's not exposed via ARM.
