### ISSUE TITLE
There is no cloud environment matching the name "AZURECLOUD"

### ISSUE THREAD

**Issue by yellowhat** [pulumi/pulumi-azure-nextgen#133]
Hi,
with the release 0.2.6, I am getting the following error:
```
error: environment "" was not found: autorest/azure: There is no cloud environment matching the name "AZURECLOUD"
```
on running `pulumi update`.

Maybe releated to [#123](https://github.com/pulumi/pulumi-azure-nextgen/issues/123)?
I cannot understand witch commit fix this issue.

Thanks

**Comment by mikhailshilkov** [comment]
Yes, it seems related. By chance, do you define the `environment` config value in your stack or `ARM_ENVIRONMENT` env variable? If yes, what is the value?

**Comment by yellowhat** [comment]
I have not set the `ARM_ENVIRONMENT` variable.
Not sure if Azure Pipeline does it for me.

**Comment by mikhailshilkov** [comment]
Which authentication method are you using? A service principal?

As a workaround, try `pulumi config set azure-nextgen:environment public` or set `ARM_ENVIRONMENT` to `public`. This shouldn't be required, but maybe we missed something.

**Comment by yellowhat** [comment]
Yes I am using the Azure DevOps service principal:
```
export ARM_CLIENT_ID="$servicePrincipalId"
export ARM_CLIENT_SECRET="$servicePrincipalKey"
export ARM_TENANT_ID="$tenantId"
export ARM_SUBSCRIPTION_ID="$( az account show --query id -o tsv )"
export AZURE_KEYVAULT_AUTH_VIA_CLI=true
export AZURE_STORAGE_KEY="..."

pulumi login azblob://"..."
pulumi stack select --create dev --secrets-provider "azurekeyvault://..."
pulumi update --yes
```

I think most of the time would be `ARM_ENVIRONMENT=public`, is it possible to have this as default, as it is on `ARM`?

Thanks

**Comment by mikhailshilkov** [comment]
> I think most of the time would be ARM_ENVIRONMENT=public, is it possible to have this as default, as it is on ARM?

Yes, that's our intention and that's how it works for me. Still trying to repro your problem...

**Comment by yellowhat** [comment]
Ok. Thanks
I do not think that Azure Pipeline define a `ARM_ENVIRONMENT` environment variable by default, that's why it is empty.
Anyway with 0.2.5 works as expected.

**Comment by mikhailshilkov** [comment]
Okay, I got the same error with an SP.  I will work on a fix to make `public` the default.

**Comment by yellowhat** [comment]
Thanks
