### ISSUE TITLE
Role assignments using the "latest" authorization package is using an old API

### ISSUE THREAD

**Issue by yarinm** [pulumi/pulumi-azure-nextgen#135]
I'm trying to run the following role assignment:

```
	_, err = authorization.NewRoleAssignment(ctx, "queue-receiver-permission", &authorization.RoleAssignmentArgs{
		Scope:              queue.ID(),
		RoleAssignmentName: pulumi.String("4f6d3b9b-027b-4f4c-9142-0e5a2a2247e0"),
		PrincipalId:        cluster.Identity.PrincipalId().Elem(),
		RoleDefinitionId:   pulumi.String(fmt.Sprintf("/subscriptions/%s/providers/Microsoft.Authorization/roleDefinitions/4f6d3b9b-027b-4f4c-9142-0e5a2a2247e0", subscriptionID)),
	}, pulumi.Provider(p))
```
When I'm using `github.com/pulumi/pulumi-azure-nextgen/sdk/go/azure/authorization/latest`
And I get the following error:
```
  azure-nextgen:authorization/latest:RoleAssignment (queue-sender-permission):
    error: Code="UnsupportedApiVersionForRoleDefinitionHasDataActions" Message="Assignments to roles with DataActions and NotDataActions are not supported on API version '2015-07-01'. The minimum required API version for this operations is '2018-01-01-preview'."
```

When I switched to `github.com/pulumi/pulumi-azure-nextgen/sdk/go/azure/authorization/v20180901preview`
The issue was resolved, but I'd expect "latest" will use the latest API..

**Comment by mikhailshilkov** [comment]
@yarinm The `latest` alias always refers to the latest *stable* API versions, as most of the time we wouldn't want users to default to fragile/experimental/short-lived previews.

In this case, I'm not sure why Azure hasn't shipped a stable version since several years ago, but our criteria stay universal.
