### ISSUE TITLE
Support user assigned identities in AKS

### ISSUE THREAD

**Issue by yarinm** [pulumi/pulumi-azure-nextgen#136]
https://docs.microsoft.com/en-us/azure/aks/use-managed-identity

**Comment by mikhailshilkov** [comment]
This will be available in the next release. You'll need to provide a dictionary where a key is an ID of the user-assigned identity and the value is an empty object (dictionary). That's odd but that's how Azure models it. 

Example usage in TypeScript:

```ts
    identity: {
        type: "UserAssigned",
        userAssignedIdentities: userIdentity.id.apply(id => {
            const dict: { [key: string] : object } = {};
            dict[id] = {};
            return dict;
        }),
    },
```
