### ISSUE TITLE
Storage Account - connection string output

### ISSUE THREAD

**Issue by jkonecki-techfabric** [pulumi/pulumi-azure-nextgen#140]
Hello,

How can I obtain connection string to storage account?

Old provider had an output called `PrimaryConnectionString` - the new one has only `PrimaryEndpoints` that do not contain connection strings.

**Comment by mikhailshilkov** [comment]
This a bit more manual with ARM. Basically, ARM doesn't export any sensitive properties by default - you have to call `list*` functions to get them. In this particular case, you need to fetch a primary key and then build the connection string. Here is an example in TypeScript: https://github.com/pulumi/templates/blob/master/azure-nextgen-typescript/index.ts#L23-L25

Here is a full example in C#: https://github.com/mikhailshilkov/azure-serverless-workshop/blob/master/02-serverless/code/step5.ts#L31-L35

**Comment by jkonecki-techfabric** [comment]
Thank you - your C# example link seems to be pointing to TypeScript code, though.

**Comment by mikhailshilkov** [comment]
Oh, I guess I'm getting crazy. Here is the best I have for C#: https://github.com/pulumi/templates/blob/master/azure-nextgen-csharp/MyStack.cs#L39

You then need to `return $"DefaultEndpointsProtocol=https;AccountName={accountName};AccountKey={accountKeys.Keys[0].Value}`"

**Comment by jkonecki-techfabric** [comment]
My scenario involves creating a storage account and adding connection string to KeyVault.

Am I supposed to invoke this async method in non-async strack constructor (block on `.Result`)? `ListStorageAccountKeysArgs` arguments are not `Inputs`, just strings - do I need to use `Apply`?

**Comment by mikhailshilkov** [comment]
You should invoke it inside an `Apply` similar to https://github.com/pulumi/templates/blob/master/azure-nextgen-csharp/MyStack.cs#L32-L33

**Comment by jkonecki-techfabric** [comment]
Please disregard my comment above - just saw the code above

**Comment by mikhailshilkov** [comment]
A full C# example here: https://github.com/pulumi/pulumi-azure-nextgen/issues/192#issuecomment-752664446
