### ISSUE TITLE
Unable to set userAssignedIdentities on application gateway

### ISSUE THREAD

**Issue by Wema** [pulumi/pulumi-azure-nextgen#141]
Hi there,
I am trying to set up application gateway with a manged identity so I can retrieve certifcates from keyvault, but I seem to be unable to set the userassigned identity for the gateway.
https://www.pulumi.com/docs/reference/pkg/azure-nextgen/network/applicationgateway/#identity_csharp

**Comment by mikhailshilkov** [comment]
This was fixed in #136 and will be released in the next version. I can see the property in the code now https://github.com/pulumi/pulumi-azure-nextgen/blob/master/sdk/dotnet/Network/Latest/Inputs/ManagedServiceIdentityArgs.cs#L30

You could temporarily switch to the latest alpha version if you are blocked on this

**Comment by MCGPPeters** [comment]
Any idea what argument to pass as the value in the InputMap<object> ?  According to the docs it should contain an empty value. How do I create an empty Input<object>?

**Comment by mikhailshilkov** [comment]
@MCGPPeters this API is a bit odd - indeed, you need to set the value to an empty object. In C# that would be "new object()".

**Comment by mikhailshilkov** [comment]
I wrote that and then realized I never tried this in C#. Let me know if it doesn't work.

**Comment by MCGPPeters** [comment]
Yeah i tried that... it does not... I tried an anonymous type or a dummy class.... => System.InvalidOperationException: Dummy is not a supported argument type....

**Comment by MCGPPeters** [comment]
btw... the docs contain an example in C# that will probably not compile => https://www.pulumi.com/docs/reference/pkg/azure-nextgen/network/applicationgateway/

**Comment by MCGPPeters** [comment]
https://github.com/pulumi/pulumi/blob/84d9947c6b9d67a0f86190a45698b10cde26db56/sdk/dotnet/Pulumi/Serialization/Serializer.cs#L238 

The serializer will throw when you pass an object, though it is required to be an object because of the type of the inputmap

**Comment by mikhailshilkov** [comment]
Try passing an empty dictionary (or ImmutableDictionary) instead of object

**Comment by MCGPPeters** [comment]
> Try passing an empty dictionary (or ImmutableDictionary) instead of object

 UserAssignedIdentities =
                    {
                        {$"/subscriptions/{subscription.Apply(result => result.Id.ToString())}/resourceGroups/<removed>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<removed>", new Dictionary<string, object>()}
                    }

worked for me
