### ISSUE TITLE
Support for ARM's listCredentials or equivalent

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-azure-nextgen#149]
I was porting some ARM logic for provisioning and publishing to an Azure Container Registry (e.g., see [this article](https://www.techdiction.com/2017/06/22/retrieving-and-using-azure-container-registry-credentials-in-an-azure-resource-manager-template/)) and ran into the need for `listCredentials`, which we don't seem to have an equivalent for (unless I am missing it). (Related to https://github.com/pulumi/pulumi-azure-nextgen/issues/37, however, this is different from many other built-ins, since it's not trivially replaceable by a language or library construct.) Is this something we intend to offer as a built-in function of this package? I can learn how to do it in the Azure SDK for each chosen language, but after a few moments of looking, that doesn't appear to be terribly straightforward.

**Comment by mikhailshilkov** [comment]
We do support it.
Docs: https://www.pulumi.com/docs/reference/pkg/azure-nextgen/containerregistry/listregistrycredentials/
Example:  https://github.com/mikhailshilkov/temporal-samples/blob/main/azure-aks/temporal.ts#L53-L59

Unless you mean arm2pulumi issues?

**Comment by mikhailshilkov** [comment]
I'll go ahead and close this. Feel free to report and further details / blockers and reopen if needed.
