### ISSUE TITLE
support enabling of docker-container-logging

### ISSUE THREAD

**Issue by imod** [pulumi/pulumi-azure-nextgen#150]
I have the need to enable log docker container logging for my webapps. 
The command to do so with a azure cli is this (https://docs.microsoft.com/en-us/cli/azure/webapp/log?view=azure-cli-latest):

```
az webapp log config --name "$APP_NAME" --resource-group "$RG_NAME" --docker-container-logging filesystem
```

Unfortunate this feature is not yet available with `nextgen`. (I could also not find it with the "old" provider)

@mikhailshilkov was pointing out it might be related to `WebApps_UpdateDiagnosticLogsConfig`

**Comment by mikhailshilkov** [comment]
Note to myself: this is likely a singleton resource under this path: https://github.com/Azure/azure-rest-api-specs/blob/c72af9b8dca625d3f1429a0bd913bad7b3879645/specification/web/resource-manager/Microsoft.Web/stable/2020-06-01/WebApps.json#L1600

**Comment by imod** [comment]
is this now supported?

**Comment by mikhailshilkov** [comment]
Sorry for not commenting - coming in 0.3.0 tomorrow.

**Comment by imod** [comment]
cool, many thanks!
