### ISSUE TITLE
Azure web app for containers "Kind" "app,linux,container"

### ISSUE THREAD

**Issue by remojansen** [pulumi/pulumi-azure-nextgen#152]
Hi, I'm trying to create an Azure web app for containers using the following code:

```ts
this.linuxAppServicePlan = new azure_nextgen.web.latest.AppServicePlan(
      name,
      {
        name: name,
        kind: "linux",
        location: this.resourceGroup.location,
        resourceGroupName: this.resourceGroup.name,
        sku: {
          name: "B1",
          tier: "Basic",
          size: "B1",
        },
      }
);

this.webApp = new azure_nextgen.web.latest.WebApp(name, {
      name: name,
      kind: "app,linux,container",
      serverFarmId: this.linuxAppServicePlan.id,
      location: this.resourceGroup.location,
      resourceGroupName: this.resourceGroup.name,
      httpsOnly: true,
});
```

I created these resources in the portal first to take a look to the ARM template. The key element seems to be the kind as `linux` for the service plan and `app,linux,container` for the web app. However, Pulumi seems to be creating a windows app plan and a standard web app. Do you have an idea of what could be wrong?

**Comment by mikhailshilkov** [comment]
I believe you should set `reserved: true,` for `AppServicePlan` (and `WebApp`?). It's a magic property that is required for a Linux plan.

**Comment by remojansen** [comment]
This solved my problem. Thanks!
