### ISSUE TITLE
Add `.LatestPreview` namespace

### ISSUE THREAD

**Issue by MisinformedDNA** [pulumi/pulumi-azure-nextgen#154]
Currently, the `.Latest` namespace represents the latest stable or preview release. 

However, [there is a need](https://github.com/pulumi/pulumi-azure-nextgen/issues/114) to only use the latest stable version.

I proposed `.Latest` be redefined as the latest stable release and `.LatestPreview` as the latest preview release.

**Comment by mikhailshilkov** [comment]
This is not accurate: currently, `latest` is always stable. We could add an alias for latest-previews or latest-anything.

**Comment by MisinformedDNA** [comment]
Yeah, I'm really confused. The `Latest` does not match up with the actual latest (stable _or_ preview):

![image](https://user-images.githubusercontent.com/1784452/100938040-93e84900-34b9-11eb-844a-90beca20a6d7.png) 
![image](https://user-images.githubusercontent.com/1784452/100938517-6cde4700-34ba-11eb-89e8-dbf56de9e173.png)

**Comment by mikhailshilkov** [comment]
That's because `latest` is calculated for each resource individually. If a resource provider has resources A and B in 2019-01-01 but B and C in 2020-01-01, `latest` will have all A, B, and C, but A coming from the earlier version.

**Comment by MisinformedDNA** [comment]
Oh, OK. Based on that, I don't care about `LatestPreview`, so I'm closing.
