### ISSUE TITLE
Not possible to configure applicationLogs as part of web app.

### ISSUE THREAD

**Issue by WillooWisp** [pulumi/pulumi-azure-nextgen#157]
There does not seem to be a way to configure the corresponding applicationLogs to azure blob storage as per the ARM template below.

```json
{
    "apiVersion": "2018-02-01",
    "type": "Microsoft.Web/sites",
    "name": "[parameters('webAppName')]",
    "location": "[parameters('location')]",
    "dependsOn": [
        "[concat('Microsoft.Web/serverfarms/', parameters('appServicePlanName'))]",
        "[concat('Microsoft.Storage/storageAccounts/', parameters('storageAccountName'))]"
    ],
    "properties": {
        "name": "[parameters('webAppName')]",
        "serverFarmId": "[concat('/subscriptions/', subscription().id,'/resourcegroups/', resourceGroup().name, '/providers/Microsoft.Web/serverfarms/', parameters('appServicePlanName'))]"
    },
    "resources": [
        {
            "apiVersion": "2018-02-01",
            "type": "config",
            "name": "logs",
            "dependsOn": [
                "[concat('Microsoft.Web/sites/', parameters('webAppName'))]"
            ],
            "properties": {
                "applicationLogs": {
                    "azureBlobStorage": {
                        "level": "[parameters('diagnosticsLogsLevel')]",
                        "sasUrl": "[concat(reference(concat('Microsoft.Storage/storageAccounts/', parameters('storageAccountName'))).primaryEndpoints.blob, variables('blobContainerName'), '?', listAccountSas(parameters('storageAccountName'), '2018-02-01', variables('listAccountSasRequestContent')).accountSasToken)]",
                        "retentionInDays": "[parameters('diagnosticsLogsRetentionInDays')]"
                    }
                }
            }
        }
    ]
}
```

**Comment by mikhailshilkov** [comment]
Thanks for reporting this! This is effectively the same issue as #150

**Comment by WillooWisp** [comment]
Okay, I cannot see a way to import a container either, using the "old" Azure provider does not seem to work, since no ImportId seems to work. In terraform you specify the container URI as the import id but that does not work here. Might be worth thinking about as well when adding support for this in the nextgen provider.

**Comment by mikhailshilkov** [comment]
You should use the ARM URL of a container in this provider. Try creating a new container and then exporting its ID to get an example.

**Comment by WillooWisp** [comment]
Thanks for quick answers, can you please explain what you mean with ARM URL and how I can export that?

**Comment by mikhailshilkov** [comment]
Storage containers can be created with the Storage SDK (via the data plane API, TF does that) or via the Azure Resource Manager API. Azure NextGen does the latter.

You could export an ID from your program `export const containerid = mycontainer.id;` and you'd get something like `/subscriptions/guid/resourceGroups/rgname/providers/Microsoft.Storage/storageAccounts/saname/blobServices/default/containers/mycontainer`.

We have an internal task to improve the docs regarding imports that would show an ID example.

**Comment by WillooWisp** [comment]
Yes that was the ID I tried with first before trying the actual storage URL as in TF. But maybe I had something wrong in it then, will try again now that I now for sure that this is the format of the ID rather than an actual URL.

**Comment by mikhailshilkov** [comment]
The new resource `WebAppDiagnosticLogsConfiguration` will be published in 0.3.0

**Comment by WillooWisp** [comment]
Nice! When is 0.3.0 to be released?

**Comment by mikhailshilkov** [comment]
It's released now - we'll update the docs later today
