### ISSUE TITLE
Not possible to configure DailyDataCap settings in AppInsights

### ISSUE THREAD

**Issue by WillooWisp** [pulumi/pulumi-azure-nextgen#158]
The "old" azure provider supports configuring the following, as does terraform:
DailyDataCapInGb = 0.1
DailyDataCapNotificationsDisabled = false

But I cannot see how this can be done with the nextgen provider for the application insights component.

**Comment by mikhailshilkov** [comment]
Note to myself: It looks like another singleton resource at https://github.com/Azure/azure-rest-api-specs/blob/44ec11c74634f1afa5bbe0d3f2678b7f819ebf8e/specification/applicationinsights/resource-manager/Microsoft.Insights/stable/2015-05-01/componentFeaturesAndPricing_API.json#L37

**Comment by mikhailshilkov** [comment]
The new resource `ComponentCurrentBillingFeature` will be published in 0.3.0
