### ISSUE TITLE
Not convenient to import a sql database since you must specify the RequestedServiceObjectiveId, which is more of an internal id.

### ISSUE THREAD

**Issue by WillooWisp** [pulumi/pulumi-azure-nextgen#159]
Importing a Database resource fails, since a matching requestedServiceObjectiveId: "<id>" setting is missing and is flagged as deleted. This should not be required to be set, since what you really want to configure is the RequestedServiceObjectiveName and the corresponding RequestedServiceObjectiveId should be inferred from that. Not sure if this only relates to import or if the Id must also be specified when applying resource without ImportId specified. But the RequestedServiceObjectiveId should never be required to be specified.

http://blog.itaysk.com/2015/09/04/create-sql-db-from-arm-template-requestedserviceobjectiveid

**Comment by mikhailshilkov** [comment]
Could you please add a repro? Thank you.

**Comment by WillooWisp** [comment]
I just updated the description, since I was a bit wrong in my first statement.

**Comment by mikhailshilkov** [comment]
Thank you for the clarification. Does that also mean that you can change the title from "not possible" to "not convenient" or something like that?

We generate resource models from API definitions and I see nothing in the API definition to make such inference a simple task for automation...

**Comment by WillooWisp** [comment]
Wouldn't it be possible to see how Terraform does it, since you do not need to specify the RequestedServiceObjectiveId there.

**Comment by mikhailshilkov** [comment]
Our current policy is to fully rely on Azure Open API specs and automation to decide which properties are needed and which not, with no manual overrides or helpers. It has upsides and downsides but it's unlikely we'll change anything manually here.

Broader improvements regarding import strictness are tracked in https://github.com/pulumi/pulumi/issues/5878, so I'll go ahead and close this issue for now.
