### ISSUE TITLE
The Swagger version specified is unknown

### ISSUE THREAD

**Issue by mastoj** [pulumi/pulumi-azure-nextgen#160]
I try to create an APIM API using an url pointing to a 3.0.1 openapi spec.

The args are defined like:

```
            ApiArgs(
                ApiId = apiId,
                Format = input "swagger-link-json",
                Path = path,
                ApiVersion = apiVersion,
                ResourceGroupName = resourceGroupName,
                ServiceName = serviceName,
                Value = swaggerUrl,
                SubscriptionRequired = subscriptionRequired
            )
```

The swaggerUrl points to the 3.0.1 spec, and running create on that args yields:

```
  azure-nextgen:apimanagement/latest:Api (apimApi):
    error: Code="ValidationError" Message="One or more fields contain incorrect values:" Details=[{"code":"ValidationError","message":"Parsing error(s): The Swagger version specified is unknown.","target":"representation"}]
```

I have tried created it manually through the portal and that works fine.

**Comment by mastoj** [comment]
Not sure what the problem is. I just changed to use swagger 2.0 but still the same problem. Is the error message referring to something wrong in the spec or something wrong with the args to the resource?

**Comment by mikhailshilkov** [comment]
Any chance you could try the same with a simple ARM template?

**Comment by mastoj** [comment]
@mikhailshilkov so the arm provider is used under the hood?

I wonder if I saw an issue that 3.0.1 isn't supported in arm somewhere. 

Will try tonight and also see if I can find that issue.

**Comment by mikhailshilkov** [comment]
We translate resources to ARM API calls as they are defined in [specs](https://github.com/Azure/azure-rest-api-specs). Usually, this means the limits/issues/service bugs are very similar to ARM templates.

**Comment by mastoj** [comment]
Got it. I did manage to convert it to version 2 and that I could deploy. So it is likely there is missing support for open api 3. But will investigate more tonight.

**Comment by mastoj** [comment]
I haven't tried using arm yet, but I did try to point to an official oai 3.0 example, https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.json, and it fails the same way. So I'm more and more convinced it is something with the ARM API. 

I also tried using the `Pulumi.Azure.ApiManagement.Api` resource since it is supposed to be fixed in terraform, https://github.com/terraform-providers/terraform-provider-azurerm/issues/3203, but that fails as well.

```
    error: creating/updating API Management API "elkjop-financialservices-financecalculator-api" (Resource Group "elkds-dev-cmn-rg"): apimanagement.APIClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ValidationError" Message="One or more fields contain incorrect values:" Details=[{"code":"ValidationError","message":"Parsing error(s): The Swagger version specified is unknown.","target":"representation"}]
```

**Comment by mastoj** [comment]
So it turns out it was user error. I was using `swagger-json-link` as format, should be `openapi-link` for open api 3.
