### ISSUE TITLE
Not getting keys upon Redis Create

### ISSUE THREAD

**Issue by kralikba** [pulumi/pulumi-azure-nextgen#162]
Hi,

The docs states that on Create/Update, the Redis object should have the access keys set. In 0.2.8, it was unset for me even in the case of creation/update.

https://github.com/pulumi/pulumi-azure-nextgen/blob/26cf650950a516640c3f705a19aed37db76b041c/sdk/dotnet/Cache/Latest/Redis.cs#L18

**Comment by mikhailshilkov** [comment]
This comment is a bit odd but it comes from the Azure Open API specs. I suspect you need to call [`ListRedisKeys`](https://www.pulumi.com/docs/reference/pkg/azure-nextgen/cache/listrediskeys/) to get the keys.

**Comment by kralikba** [comment]
Yes, I did call exactly that; it works that way.

Oh I see. I thought that this came from some lower level, hence the raised issue. As per formal logic, the sentence does not imply that I should be expecting a value on a Create/Update, but it is nevertheless is misleading for humans.

**Comment by mikhailshilkov** [comment]
I'll go ahead and close this issue since there are no action items here for us

**Comment by kralikba** [comment]
Posted issue to https://github.com/Azure/azure-rest-api-specs/issues/12082
