### ISSUE TITLE
getWorkspace does not return id

### ISSUE THREAD

**Issue by imod** [pulumi/pulumi-azure-nextgen#165]
To create a new `DiagnosticSetting` (https://www.pulumi.com/docs/reference/pkg/azure-nextgen/insights/diagnosticsetting/) I need the Id of an existing `Workspace` (https://www.pulumi.com/docs/reference/pkg/azure-nextgen/operationalinsights/workspace/) therefore I use the `getWorkspace` function (https://www.pulumi.com/docs/reference/pkg/azure-nextgen/operationalinsights/getworkspace/) to get hold on the workspace.

But unfortunate the `GetWorkspace Result` does not include the id.

```
import * as operationalinsights from "@pulumi/azure-nextgen/operationalinsights/v20200801";

export const workspaceId = operationalinsights.getWorkspace({
    resourceGroupName: `yoo-env-${environment}`,
    workspaceName: `yoo-logs-${environment}`,
  })
  .then((w) => w.id); // -> fails, because id is not available
```

I would like to avoid to compose the id myself by concatenating all different kinds of informations like this: `/subscriptions/${subscription}/resourcegroups/${resourceGroup}/providers/microsoft.operationalinsights/workspaces/${workspaceName}` I think this should be handled internally by `nextgen`. 

It would be very helpful to have the id of the workspace exposed.

**Comment by mikhailshilkov** [comment]
Let's track this in https://github.com/pulumi/pulumi-azure-nextgen/issues/48
