### ISSUE TITLE
Not possible to import app service plan

### ISSUE THREAD

**Issue by WillooWisp** [pulumi/pulumi-azure-nextgen#166]
I am unable to import the app service plan itself using the new AppServicePlan resource, other resources works fine. It also works with the same import id in the old azure provider using the Plan resource.

ImportId = $"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/serverfarms/{appServicePlanName}"

error: Preview failed: autorest/azure: Service returned an error. Status=400 Code="NoRegisteredProviderFound" Message="No registered resource provider found for location 'northeurope' and API version '2020-09-01' for type 'serverFarms'. The supported api-versions are '2020-06-01, 2019-08-01, 2018-11-01, 2018-02-01, 2017-08-01, 2016-09-01, 2016-03-01, 2015-08-01, 2015-07-01, 2015-06-01, 2015-05-01, 2015-04-01, 2015-02-01, 2014-11-01, 2014-06-01, 2014-04-01, 2014-04-01-preview, 2018-12-01-alpha'. The supported locations are 'southcentralus, msftwestus, msfteastus, msfteastasia, msftnortheurope, eastus2stage, centralusstage, southafricanorth, westus, australiaeast, brazilsouth, southeastasia, centralus, japanwest, centralindia, uksouth, canadaeast, koreacentral, francecentral, westus2, eastus, westindia, eastus2, australiacentral, germanywestcentral, norwayeast, uaenorth, switzerlandnorth, northcentralus, ukwest, australiasoutheast, koreasouth, canadacentral, westeurope, southindia, westcentralus, eastasiastage, northcentralusstage, eastasia, japaneast, northeurope'."
error: preview failed

**Comment by mikhailshilkov** [comment]
It looks like Azure hasn't deployed the latest API version to this region yet. Try replacing `Web.Latest` with `Web.V20200601` in the usings.

**Comment by WillooWisp** [comment]
Ahh, okay, makes sense, thanks that worked!

**Comment by mikhailshilkov** [comment]
Opened https://github.com/pulumi/pulumi-azure-nextgen/issues/170 to make this experience better
