### ISSUE TITLE
Azure Event Hubs Namespace Network Rules and IoT Hub Resource Identity Property missing.

### ISSUE THREAD

**Issue by bantoni** [pulumi/pulumi-azure-nextgen#17]
Hi,

after playing around for a while, I figured out that certain parts of the ARM APIs are not included.

For example, the Pulumi.AzureNextGen.Devices.V20200710Preview.IotHubResourceArgs does not include the identity property, which is definitely available in ARM templates.
For Pulumi.AzureNextGen.EventHub.V20180101Preview, the network rule sets do not seem to be supported as documented here: https://docs.microsoft.com/en-us/rest/api/eventhub/2018-01-01-preview/network%20rule%20sets

I'm not sure whether this is a bug, not implemented yet or by intention.

Regards
Benedikt

**Comment by mikhailshilkov** [comment]
> IotHubResourceArgs does not include the identity property

I'm not greatly familiar with this resource. Do you see the properties you are looking for in [this spec](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/iothub/resource-manager/Microsoft.Devices/preview/2020-07-10-preview/iothub.json)?

> the network rule sets do not seem to be supported 

This is a known limitation. That resource doesn't implement a DELETE operation that is currently required by our resource model (to undo the effect on resource destruction). However, we are planning to add such resources in the upcoming releases pretty soon.

I hope this helps, thanks for your feedback!

**Comment by bantoni** [comment]
Interesting. I don't find the property in the spec.
But when I export my IoT Hub resource via Azure Portal, it generates the template including the identity property as follows:
```
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "iotHubName": {
            "defaultValue": "iot-hub-with-system-assigned-identity-hdu48fh",
            "type": "String"
        }
    },
    "variables": {},
    "resources": [
        {
            "type": "Microsoft.Devices/IotHubs",
            "apiVersion": "2020-07-10-preview",
            "name": "[parameters('iotHubName')]",
            "location": "westeurope",
            "sku": {
                "name": "S1",
                "tier": "Standard",
                "capacity": 1
            },
            "identity": {
                "type": "SystemAssigned"
            },
            "properties": {
                "ipFilterRules": [],
                "eventHubEndpoints": {
                    "events": {
                        "retentionTimeInDays": 7,
                        "partitionCount": 4
                    }
                },
                "storageEndpoints": {},
                "messagingEndpoints": {
                    "fileNotifications": {
                        "lockDurationAsIso8601": "PT1M",
                        "ttlAsIso8601": "PT1H",
                        "maxDeliveryCount": 10
                    }
                },
                "enableFileUploadNotifications": false,
                "cloudToDevice": {
                    "maxDeliveryCount": 10,
                    "defaultTtlAsIso8601": "PT1H",
                    "feedback": {
                        "lockDurationAsIso8601": "PT1M",
                        "ttlAsIso8601": "PT1H",
                        "maxDeliveryCount": 10
                    }
                },
                "features": "None"
            }
        }
    ]
}
```
I can also deploy a new IoT Hub this way as I'd expect it. I don't have a clue where this property originates from.


Thanks for the clarification regarding the network rule sets.

**Comment by mikhailshilkov** [comment]
Azure Event Hubs Namespace Network Rules will appear in the next release.
We'll track IoT Hub Resource Identity Property upstream in the Open API specs.
