### ISSUE TITLE
Setting KeyVault keys, secrets, etc. requires a strange cast

### ISSUE THREAD

**Issue by MisinformedDNA** [pulumi/pulumi-azure-nextgen#173]
Within KeyVault's Permission object, I want to be able to easily set a string or a list of strings as keys.

The Azure package allows 

```csharp
Keys =
{
    "encrypt"
}
```

but in AzureNextGen, this is required:

```csharp
Keys =
{
    (Union<string, KeyPermissions>)"encrypt"
}
```

Digging deeper, the types have changed

Azure:
```csharp
InputList<string> Keys
```

AzureNextGen*:

```csharp
InputList<Union<string, KeyPermissions>> Keys
```

`Union`'s comments say "This is used to hold a value that could take on several different, but fixed, types.

This seems like unnecessary complexity. Couldn't we just have:

```csharp
InputList<KeyPermissions> Keys
```

and then cast all the strings to `KeyPermissions`?

```csharp
Keys = 
{
    (KeyPermission)"encrypt", // or
    KeyPermissions.Parse("encrypt")
}
```

\* The metadata of v0.3.0 shows the type `InputList<Union<string, KeyPermissions>>`, but the source code shows [`InputList<string>`](https://github.com/pulumi/pulumi-azure-nextgen/blob/master/sdk/dotnet/KeyVault/V20180214/Inputs/PermissionsArgs.cs#L36). I'm not sure why they are different.

@mikhailshilkov

**Comment by MisinformedDNA** [comment]
@mikhailshilkov

**Comment by mikhailshilkov** [comment]
> This seems like unnecessary complexity.

Azure describes this enum as open, where client-side validation shouldn't restrict the value to the given set but accept any user input. The enum values are there as hints but not a limitation. We could model this as a plain `string` (that's what the spec suggests) but we also wanted to add extra help for users.

We'll see if we can make the developer experience more pleasant.

**Comment by MisinformedDNA** [comment]
Let me think on this. In the meantime, why does the metadata not match the source code? Am I looking at the wrong source?

**Comment by MisinformedDNA** [comment]
@mikhailshilkov  With one line added

```csharp
public static implicit operator KeyPermissions(string value) => new KeyPermissions(value);
```

This works fine:

```csharp
var keyPermissions = new List<KeyPermissions>
{ 
    KeyPermissions.Encrypt,
    "whatever"
};
```

The `Union`/`OneOf` thing is pretty cool, but it seems like an unnecessary complication.

**Comment by mikhailshilkov** [comment]
The issues got closed by the upstream PR - we'll ship the improvement in 0.3.1

**Comment by MisinformedDNA** [comment]
Yes, I see that you improved the casting to `Union`, but why have `Union` at all? Having multiple types only increases complexity and confusion where one type handles things just fine.

**Comment by mikhailshilkov** [comment]
I hear you. To some extent, this is our implementation details leaked out to the .NET type system. We won't change it right now but please file an issue in pulumi/pulumi (which generates this code) if you think it's important.
