### ISSUE TITLE
API missing for creating an IoT hub?

### ISSUE THREAD

**Issue by WillooWisp** [pulumi/pulumi-azure-nextgen#174]
I cannot seem to find any resource for creating an IoT hub in the documentation.

**Comment by mikhailshilkov** [comment]
Have you tried these https://www.pulumi.com/docs/reference/pkg/azure-nextgen/devices/ ?

**Comment by WillooWisp** [comment]
No, devices, interesting, will try it right away, thanks!

**Comment by mikhailshilkov** [comment]
Yeah, the names aren't always easy to guess. I usually google something like "arm template iot hub" to look up the right resource provider and resource names.
