### ISSUE TITLE
Importing an IotHubResource fails due to incorrect properties being marked for deletion

### ISSUE THREAD

**Issue by WillooWisp** [pulumi/pulumi-azure-nextgen#176]
These properties become marked as removed, but they are not possible to configure and not part of the exported ARM template either. There seems to be something going wrong during import.

properties: {
          ~ eventHubEndpoints: {
              ~ events: {
                  - endpoint    : "sb://iothub-ns-mytestdev-2234261-ef3eeecaff.servicebus.windows.net/"
                  - partitionIds: [
                  -     [0]: "0"
                  -     [1]: "1"
                    ]
                  - path        : "mytestdev-iothub"
                }
            }

**Comment by mikhailshilkov** [comment]
To be fixed in 0.4.0

**Comment by WillooWisp** [comment]
Nice, when is this expected to be released?

**Comment by mikhailshilkov** [comment]
It's already released now
