### ISSUE TITLE
Hard to find the right value for Constant properties

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure-nextgen#180]
In the following code, if I do not supply a value for the `Type` field in the respective `Args` types, the pulumi runtime fails, sometimes with a grpc serialization error, and sometimes with an error from the azure API.

When `Type` is populated, everything works, but the value could/should be included by the containing class instead of supplied by me. It’s hard to figure out what the right value for `Type` is—I’ve been building sample objects in the portal, then exporting their ARM templates to find out what the correct value is.

![image](https://user-images.githubusercontent.com/1454008/102192353-f4fd1d00-3eba-11eb-8686-bde36fed901b.png)

(from a user question)

**Comment by viveklak** [comment]
Starting in v0.3.1 descriptions include the const values.

**Comment by mikhailshilkov** [comment]
A better fix of not requiring this property at all is tracked as part of https://github.com/pulumi/pulumi-azure-nextgen/issues/19
