### ISSUE TITLE
`default` property is ignored

### ISSUE THREAD

**Issue by MisinformedDNA** [pulumi/pulumi-azure-nextgen#183]
In the specs, properties can have [default values](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/storage/resource-manager/Microsoft.Storage/stable/2019-06-01/storage.json#L1879):

```json
"keySource": {
  "type": "string",
  "description": "The encryption keySource (provider). Possible values (case-insensitive):  Microsoft.Storage, Microsoft.Keyvault",
  "enum": [
    "Microsoft.Storage",
    "Microsoft.Keyvault"
  ],
  "x-ms-enum": {
    "name": "KeySource",
    "modelAsString": true
  },
  "default": "Microsoft.Storage"
},
```

Those defaults are not reflected [in the SDK](https://github.com/pulumi/pulumi-azure-nextgen/blob/master/sdk/dotnet/Storage/Latest/Inputs/EncryptionArgs.cs#L21-L22):

```csharp
[Input("keySource", required: true)]
public InputUnion<string, Pulumi.AzureNextGen.Storage.Latest.KeySource> KeySource { get; set; } = null!;
```

The SDK should have:

```csharp
[Input("keySource"]
public InputUnion<string, Pulumi.AzureNextGen.Storage.Latest.KeySource>? KeySource { get; set; } ;
```

**Comment by mikhailshilkov** [comment]
Default values will be respected in the next version
