### ISSUE TITLE
Union properties are barely usable in C#

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure-nextgen#19]
`InputUnion`, when nested with other InputUnion objects, does not work as designed.

The following code should be valid, but isn’t. `ParquetDatasetArgs` is present in the very long list of nested `InputUnion` types—but the compiler will not convert it as it seems like it is designed to

![image](https://user-images.githubusercontent.com/1454008/94260951-54d5ce80-ff31-11ea-942b-b056b16cdbb0.png)

results in a very long error message `error CS0029: Cannot implicitly convert type ...`

**Comment by mikhailshilkov** [comment]
Indeed, we overestimated the power of implicit conversions in C#, which fall flat in unions with more than two type members. It's likely we need to re-design the type representation to class hierarchies instead of using union types.

Meanwhile, I have a very hacky workaround that can hopefully unblock anyone for the time being.

Add the following helper class:

```cs
public static class UnionConverter
{
    public static dynamic ConvertToInputUnion(PropertyInfo property, object value) =>
        ConvertToInputUnionImpl(property.PropertyType, value);

    private static dynamic ConvertToInputUnionImpl(Type type, object value)
    {
        var genericType = type.GetGenericTypeDefinition();
        if (genericType != typeof(InputUnion<,>))
            throw new Exception("Expected an InputUnion<T0, T1> type");
        var leftType = type.GetGenericArguments()[0];
        if (value.GetType() == leftType)
        {
            var leftConverter = type.GetMethod("op_Implicit", new[] { leftType });
            return leftConverter.Invoke(null, new[] { value });
        }
        
        var rightType = type.GetGenericArguments()[1];
        var converter = type.GetMethod("op_Implicit", new[] { rightType });
        if (value.GetType() == rightType)
        {
            return converter.Invoke(null, new[] { value });
        }

        var recursiveResult = ConvertToInputUnionImpl(rightType, value);
        return converter.Invoke(null, new[] { recursiveResult });
    }
}
```

And here is a simple usage example:

```cs
var a = new ActionRuleByName("", new ActionRuleByNameArgs
{
    // ... other properties
    Properties = UnionConverter.ConvertToInputUnion(
        typeof(ActionRuleByNameArgs).GetProperty(nameof(ActionRuleByNameArgs.Properties)),
        new DiagnosticsArgs
        {
            // other properties...
        })
});
```

and a more sophisticated example:

```cs
var locationProperty = typeof(ParquetDatasetArgs).GetProperty(nameof(ParquetDatasetArgs.Location));
var parquetLocation = new FileServerLocationArgs
{
    Type = "FileServerLocation",
};

var propertiesProperty = typeof(DatasetArgs).GetProperty(nameof(DatasetArgs.Properties));
var parquetDataset = new ParquetDatasetArgs
{
    Location = UnionConverter.ConvertToInputUnion(locationProperty, parquetLocation),
    LinkedServiceName = new LinkedServiceReferenceArgs
    {
        ReferenceName = "ADLSNexusTest",
        Type = "LinkedServiceReference"
    },
    Type = "Parquet"
};
var dataset = new Dataset("dataset", new DatasetArgs
{
    DatasetName = "exampleDataset",
    FactoryName = "exampleFactoryName",
    ResourceGroupName = "exampleResourceGroup",
    Properties = UnionConverter.ConvertToInputUnion(propertiesProperty, parquetDataset)
});
```

**Comment by william-liebenberg** [comment]
Thanks for the helper @mikhailshilkov 

This issue had me stumped for a few hours today -- I rewrapped the types by hand and was hoping that this surely wasn't by design. Then lucky I found this post :)

The worst was trying to map `Pulumi.AzureNextGen.StreamAnalytics.V20170401Preview.Inputs.EventHubOutputDataSourceArgs` onto  `Pulumi.AzureNextGen.StreamAnalytics.V20170401Preview.Inputs.OutputArgs.DataSource`.

Any idea what the "next version" will be like to solve this issue?

**Comment by mikhailshilkov** [comment]
@william-liebenberg Sorry for the trouble - the current types are indeed troublesome.

> Any idea what the "next version" will be like to solve this issue?

It feels natural to generate this as one base class and N inherited classes in C#. They all share a base class property ("discriminator") but each sub-class returns its own const value as the value of that property. I haven't done any experimentation with this yet, though.

Any further ideas or opinions are certainly welcome!

**Comment by william-liebenberg** [comment]
No worries - that helper made a big difference -- got my work over the line before the end of the day :)

Yea a more traditional OO solution might be more suited to C#, or even some sort of `Func<>` helper methods could work...

I guess for the example below the DocumentDbOuptuDataSourceArgs would already be new'd up and some of the required defaults already set ... we just add our own customizations and return it back...

```
// assuming the namespace: Pulumi.AzureNextGen.StreamAnalytics.V20170401Preview

Input<OutputArgs> streamAnalyticsCosmosDbOutput = Inputs.OutputArgs.CreateCosmosDbOutput("outputName", dataSource => 
{
    // datasource = Pulumi.AzureNextGen.StreamAnalytics.V20170401Preview.Inputs.DocumentDbOutputDataSourceArgs

    dataSource.AccountId = "myCosmosAccount";
    dataSource.AccountKey =  "xyz";
    dataSource.Database = "myCosmosDatabase";
    dataSource.CollectionNamePattern= "myContainer";
    dataSource.DocumentId= "123abc";

    return dataSource;
});
```
This idea might need a bit of massaging to get working... 

What do you think?

**Comment by nathanwinder-perficient** [comment]
I ran into this trying to create DeliveryPolicy rules for a CDN Endpoint. You could do something like this:
```csharp
 DeliveryPolicy = new EndpointPropertiesUpdateParametersDeliveryPolicyArgs
                {
                    Rules = new DeliveryRuleArgs
                    {
                        Name = "deeplinkredirect",
                        Order = 1,
                        Actions = DeliveryRuleActionsFactory.Create(actions=> 
                        {
                            actions.Add(new UrlRewriteActionArgs{ ... });
                            actions.Add(new DeliveryRuleCacheKeyQueryStringActionArgs{ ... });
                        })
                        
                    }
                }
```
The overloads of `Add` would be typed but your underlying store would be a List of a common base class. This is only slightly better than just having a base class because it will provide the developers with intellisense for the possible types. Resharper provides subclass intellisense but I'm not sure vanilla Visual Studio does. But if you go with a common base class you could add the Factory as an optional tool for those that want to use it.

And when accessing the Output<>:
```csharp
endpoint.DeliveryPolicy.Rules.Actions.Select(a=> a switch {
  UrlRewriteActionArgs args => ....,
  DeliveryRuleCacheKeyQueryStringActionArgs => ...,
})
``` 
or
```chsarp
foreach(var action in endpoint.DeliveryPolicy.Rules.Actions)
{
  if(action is UrlRewriteActionArgs rewriteAction){ 
    ...
  } else if ( action is DeliveryRuleCacheKeyQueryStringActionArgs cacheKeyAction){
    ...
  }
}
```
C# developers don't have the luxury of Union types so they wont be missing anything.

**Comment by mikhailshilkov** [comment]
Related: we could also fix https://github.com/pulumi/pulumi-azure-nextgen/issues/180 if we introduce class hierarchies here

**Comment by mikhailshilkov** [comment]
Release 0.4.0 replaces all nested union types with plain `object`. We lose type "safety" here but it was there only formally, as the workaround above is fully based on reflection. `object` will require less ceremony for now.

We'll keep watching how good/bad the user experience is here and tracking inheritance-based solution as a follow-up.
