### ISSUE TITLE
Creating Key in Vault - Cannot check existence of resource

### ISSUE THREAD

**Issue by kralikba** [pulumi/pulumi-azure-nextgen#195]
Hi,

When trying to create a key in a vault, I get the following error message:
```
cannot check existence of resource '/subscriptions/[REDACTED]/resourceGroups/[REDACTED]/providers/Microsoft.KeyVault/vaults/[REDACTED]/keys/[REDACTED]': 
status code 400, {"error":{"code":"ForbiddenByRbac","message":"[ForbiddenByRbac (Forbidden)] Caller is not authorized to perform action on resource.\r\n
If role assignments, deny assignments or role definitions were changed recently, please observe propagation time.\r\n
Caller: name=KeyVault/ManagementPlane;appid=[REDACTED];oid=[REDACTED];iss=https://sts.windows.net/[REDACTED]/\r\n
Action: 'Microsoft.KeyVault/vaults/keys/read'\r\nResource: '/subscriptions/[REDACTED]/resourcegroups/[REDACTED]/providers/microsoft.keyvault/vaults/[REDACTED]/keys/[REDACTED]'\r\n
Assignment: (not found)\r\nVault: [REDACTED];location=westeurope\r\n"}}
```

The current user has all permissions explicitly granted in the vault's access policy.

Manually creating keys using the azure cli or the web ui works.

Could you please help/point me to a working example where a key is created using this provider?

**Comment by mikhailshilkov** [comment]
We have a test in our CI/CD which creates Key Vault keys. This works for us but not for you, so we need to figure out the difference. Do you happen to have a simple repro that I could run in isolation to reproduce?

**Comment by mikhailshilkov** [comment]
Our working example:

```ts
import * as random from "@pulumi/random";
import * as keyvault from "@pulumi/azure-nextgen/keyvault/latest";
import * as resources from "@pulumi/azure-nextgen/resources/latest";

const randomString = new random.RandomString("random", {
    length: 12,
    special: false,
    upper: false,
    number: false,
}).result;

const resourceGroup = new resources.ResourceGroup("rg", {
    resourceGroupName: randomString,
    location: "westus2",
});

// TODO: read IDs with an invoke when it's available
// https://github.com/pulumi/pulumi-azure-nextgen/issues/107
const tenantId = "guid";
const currentPrincipalId = "guid";

const vault = new keyvault.Vault("vault", {
    resourceGroupName: resourceGroup.name,
    location: resourceGroup.location,
    vaultName: randomString,
    properties: {
        accessPolicies: [{
            objectId: currentPrincipalId,
            permissions: {
                keys: [
                    keyvault.KeyPermissions.Get,
                    keyvault.KeyPermissions.Create,
                    keyvault.KeyPermissions.Delete,
                    keyvault.KeyPermissions.List,
                    keyvault.KeyPermissions.Recover,
                    keyvault.KeyPermissions.Purge,
                ],
                secrets: [
                    keyvault.SecretPermissions.Get,
                    keyvault.SecretPermissions.List,
                    keyvault.SecretPermissions.Set,
                    keyvault.SecretPermissions.Delete,
                    keyvault.SecretPermissions.Recover,
                    keyvault.SecretPermissions.Purge,
                ],
            },
            tenantId,
        }],
        sku: {
            family: keyvault.SkuFamily.A,
            name: keyvault.SkuName.Standard,
        },
        tenantId,
    },
});

const secret = new keyvault.Secret("mysecret", {
    resourceGroupName: resourceGroup.name,
    vaultName: vault.name,
    secretName: "mysecret",
    properties: {
        value: "myvalue",
    },
});

const key = new keyvault.Key("mykey", {
    resourceGroupName: resourceGroup.name,
    vaultName: vault.name,
    keyName: "mykey",
    properties: {
        kty: "RSA",
        keySize: 2048,
        keyOps: [
            "decrypt",
            "encrypt",
            "sign",
            "unwrapKey",
            "verify",
            "wrapKey",
        ],
    },
});
```

**Comment by kralikba** [comment]
I don't see any apparent difference. Can it be that I'm using a wrong current principal id? How do you get yours? (I'm looking up my user's ID from Azure AD)

**Comment by mikhailshilkov** [comment]
If you are authenticating with a user (not a service principal), then it's the user object ID that you can see with `az ad signed-in-user show --query objectId`

**Comment by mikhailshilkov** [comment]
You can now also get your object ID programmatically as shown in https://github.com/pulumi/pulumi-azure-nextgen/issues/107#issuecomment-754538898

I'll go ahead and close the issue for now - let me know if you still experience it after this change

**Comment by kralikba** [comment]
Hi,

Please reopen the issue. I’ve created a minimal nonworking example. See: https://github.com/kralikba/pulumi-akv

Best
Barnabás Králik

**Comment by mikhailshilkov** [comment]
@kralikba thank you for the repro.

I had to change the key to `Kty = "RSA",` (you have a typo?) and then your example works like charm for me.

**Comment by kralikba** [comment]
@mikhailshilkov nice catch of that typo. However, this has not solved the issue; I still get the same ForbiddenByRbac error from Azure:

```
Previewing update (demo):
     Type                                  Name          Plan
     pulumi:pulumi:Stack                   akvdemo-demo
 +   └─ azure-nextgen:keyvault/latest:Key  k             create

Resources:
    + 1 to create
    4 unchanged

Permalink: file:///D:/tpg/git/pulumi-akv/pulumi-akv/.pulumi/stacks/demo.json
Updating (demo):
     Type                                  Name          Status                  Info
     pulumi:pulumi:Stack                   akvdemo-demo  **failed**              1 error
 +   └─ azure-nextgen:keyvault/latest:Key  k             **creating failed**     1 error

Diagnostics:
  pulumi:pulumi:Stack (akvdemo-demo):
    error: update failed

  azure-nextgen:keyvault/latest:Key (k):
    error: cannot check existence of resource '/subscriptions/<<SUBSCRIPTIONID>>˛/resourceGroups/test-akv/providers/Microsoft.KeyVault/vaults/qmjdsnpnonyl/keys/key': status code 400, {"error":{"code":"ForbiddenByRbac","message":"[ForbiddenByRbac (Forbidden)] Caller is not authorized to perform action on resource.\r\nIf role assignments, deny assignments or role definitions were changed recently, please observe propagation time.\r\nCaller: name=KeyVault/ManagementPlane;appid=04b07795-8ddb-461a-bbee-02f9e1bf7b46;oid=<<MYID>>;iss=https://sts.windows.net/<<TENANTID>>/\r\nAction: 'Microsoft.KeyVault/vaults/keys/read'\r\nResource: '/subscriptions/<<SUBSCRIPTIONID>>/resourcegroups/test-akv/providers/microsoft.keyvault/vaults/qmjdsnpnonyl/keys/key'\r\nAssignment: (not found)\r\nVault: qmjdsnpnonyl;location=westeurope\r\n"}}

Resources:
    4 unchanged

Duration: 4s
```

**Comment by mikhailshilkov** [comment]
Can this be something specific about your subscription? I tested it both with a user and a service principal and it just works... Are you able to create a key with the same user/sp via CLI or SDK or ARM template? I think we need to figure out the difference in our setups.

**Comment by kralikba** [comment]
I'm logged in with an Azure AD user; I've just used `az login`. The same user can both list keys and create new ones using `az` and get a correct "was not found" error for nonexistent names.
I haven't tried the SDK or ARM templates directly.

**Comment by mikhailshilkov** [comment]
You should be able to see the failed request to create a key in the activity log of the vault. Can you see your user ID there? If it matches, could you file a support ticket to figure out why it failed?

**Comment by kralikba** [comment]
There is nothing in the activity log of the vault nor are any diagnostic messages generated.

I have captured traffic with Fiddler to see what is happening. 
There is only one request/response. It is a GET that goes to `management.azure.com/subscriptions/<<Correct SubscriptionId>>/resourceGroups/test-akv/providers/Microsoft.KeyVault/vaults/<<vault id>>/keys/key?api-version=2019-09-01`. No application-specific headers are present in the request. The response is the same ForbiddenByRbac error message.

But I see why the CLI works: that one is accessing the vault directly on `https://vaultaname.vault.azure.net/keys/key1/?api-version=7.0`.

**Comment by mikhailshilkov** [comment]
Indeed, we go through ARM API (as with all other resources) which is a newer endpoint compared to the data-plane API that others are still using. This doesn't explain the authentication failure though (again, it works for us and 100% worked for other users).
