### ISSUE TITLE
Missing ability to add NS Record Set

### ISSUE THREAD

**Issue by SamuelMcAravey** [pulumi/pulumi-azure-nextgen#196]
It seems that the ability to add NS Record Sets to an Azure DNS Zone is missing. The relevant links:

ARM Template Docs: https://docs.microsoft.com/en-us/azure/templates/microsoft.network/dnszones/ns
Pulumi Docs: https://www.pulumi.com/docs/reference/pkg/azure-nextgen/network/recordset/

The Azure Portal provides the ability to create "child DNS zones", which are really just NS records added to the parent DNS Zone. There does not appear to be a specific "child DNS zones" capability in ARM templates, and with the ability to manually add NS records missing we have to fall back to the original Pulumi Azure provider to accomplish that.

**Comment by mikhailshilkov** [comment]
There's a bit of a mess with API versions here which is tracked in https://github.com/pulumi/pulumi-azure-nextgen/issues/67

I believe you should use `v20180501`, e.g. in TypeScript https://github.com/pulumi/pulumi-azure-nextgen/blob/14d7b054a3ba2371919312262dbee325c1a848f2/sdk/nodejs/network/v20180501/recordSet.ts#L77, see https://github.com/pulumi/pulumi-azure-nextgen/issues/67#issuecomment-753375218
