### ISSUE TITLE
Invoke to get storage SAS signature

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure-nextgen#201]
Provide an example and/or support first-class building SAS tokens for Storage Blobs/Containers as in https://github.com/pulumi/examples/blob/71a72d70d43a48c77c63fc570013e040f8ae9923/azure-nextgen-ts-functions/helpers.ts#L17 but with the nextgen provider

**Comment by WillooWisp** [comment]
Since this is missing I now try to use Pulumi.Azure.Storage.GetAccountBlobContainerSAS.InvokeAsync but then I get an error during preview when no storage account exist yet. Will the fix to this issue solve that, so that everything can be applied from scratch?

**Comment by WillooWisp** [comment]
That is probably not the problem since ListStorageAccountKeys.InvokeAsync does not work for me either. But how can it work when not able to specify any dependency on the resource or resource group indicating the order of creation?

**Comment by mikhailshilkov** [comment]
Are you calling it from within an `Apply` as shown in https://github.com/pulumi/templates/blob/master/azure-nextgen-csharp/MyStack.cs#L33 ? This would make a dependency between the resource and its invoke.

**Comment by WillooWisp** [comment]
Ahh, will try that, thanks!

**Comment by WillooWisp** [comment]
Worked like a charm, feels quite obvious now!

**Comment by mikhailshilkov** [comment]
Version 0.6.0 includes [`ListStorageAccountSAS`](https://www.pulumi.com/docs/reference/pkg/azure-nextgen/storage/liststorageaccountsas/) and [`ListStorageAccountServiceSAS`](https://www.pulumi.com/docs/reference/pkg/azure-nextgen/storage/liststorageaccountservicesas/) invokes
