### ISSUE TITLE
Support Azure Postgres Flexible Server Preview API

### ISSUE THREAD

**Issue by elsesiy** [pulumi/pulumi-azure-nextgen#208]
I don't see the preview API for Azure Postgres Flexible servers available via Pulumi yet.

https://github.com/Azure/azure-sdk-for-go/tree/master/services/preview/postgresql/mgmt/2020-02-14-preview/postgresqlflexibleservers

Any chance we can get that added?

Thanks!

**Comment by mikhailshilkov** [comment]
Somewhat confusingly, the API specs refer to them as just "Servers". I'm quite sure this is a "flexible server" though: https://github.com/pulumi/pulumi-azure-nextgen/blob/master/sdk/go/azure/dbforpostgresql/v20200214preview/server.go as it talks to the path `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DBForPostgreSql/flexibleServers/{serverName}`

**Comment by elsesiy** [comment]
My bad, that looks correct. Thanks @mikhailshilkov!

**Comment by mikhailshilkov** [comment]
We base our naming on Operation ID. None of path or operation ID match reliably to common marketing names, but operation IDs a) are closer b) have canonical casing c) are used for Azure SDKs (like [here](https://github.com/Azure/azure-sdk-for-go/blob/master/services/preview/postgresql/mgmt/2020-02-14-preview/postgresqlflexibleservers/servers.go#L32)), so we went with them
