### ISSUE TITLE
Unrecoverable failure when creating Certificate resource

### ISSUE THREAD

**Issue by DaRosenberg** [pulumi/pulumi-azure-nextgen#212]
There is an issue with the new provider when creating `Certificate` resources.

```cs
var certificate = new Pulumi.AzureNextGen.Web.V20190801.Certificate(
	$"orgflow-download-{stackName}-cert",
	new Pulumi.AzureNextGen.Web.V20190801.CertificateArgs()
	{
		Name = $"orgflow-download-{stackName}-cert",
		ResourceGroupName = resourceGroup.Name,
		Location = location,
		CanonicalName = publicHostname,
		ServerFarmId = appServicePlan.Id,
		Password = ""
	},
	new ResourceOptions()
	{
		// App Service Managed Certificates cannot be created unless a hostname binding has already
		// been added to the corresponding app service.
		DependsOn = hostnameBinding
	});
```

This creates an Azure-managed app service certificate for a web app. However,` pulumi up` fails on this resource with the following error:

```
azure-nextgen:web/v20190801:Certificate (orgflow-download-dev-cert):
  error: autorest/azure: error response cannot be parsed: "" error: EOF
```

Pulumi exits with a failure, and thinks the resource has not been created, but the **certificate is actually created successfully in Azure**. Next time we do `pulumi up` it fails because the resource is already there. So this one seems to be more of an issue with how Pulumi is handling a response from the API, rather than a failure to do the deployment.

**Comment by mikhailshilkov** [comment]
We fail because we get 202 where we don't expect it. I opened an upstream issue https://github.com/Azure/azure-rest-api-specs/issues/12431

Meanwhile, I'll submit a workaround to our code.
