### ISSUE TITLE
Improve error messaging

### ISSUE THREAD

**Issue by MisinformedDNA** [pulumi/pulumi-azure-nextgen#213]
When trying to create a SQL Server (with an invalid username), `pulumi up` fails with a bizarre error message:

> error: json: cannot unmarshal array into Go struct field serviceError2.details of type map[string]interface

## Expected Behavior:

I get the Azure response status code and body.

## Actual Behavior:

I get a error message that instead gives me seemingly useless information with no sign of where to go or what went wrong.

Also, since my stack is in C#, I don't think I should ever see a Go error, which may imply that the error is in the core Pulumi code.

## Steps to Reproduce:

1. Deploy the following stack:

    ```
    using Pulumi;
    using Pulumi.AzureNextGen.Resources.Latest;
    using Pulumi.AzureNextGen.Sql.Latest;
    
    internal class MyStack : Stack
    {
        public MyStack()
        {
            string resourceGroupName = "my-rg";
            string location = "WestUS";
            string sqlServerName = "someServer20210108";
            string sqlAdministratorLogin = "admin";
            string sqlAdministratorPassword = "Password1!";
            var resourceGroup = new ResourceGroup("resourceGroup", new ResourceGroupArgs
            {
                ResourceGroupName = resourceGroupName,
                Location = location,
            });
            new Server("sqlServer", new ServerArgs
            {
                ServerName = sqlServerName,
                ResourceGroupName = resourceGroup.Name,
                Location = location,
                AdministratorLogin = sqlAdministratorLogin,
                AdministratorLoginPassword = sqlAdministratorPassword,
            });
        }
    }
    ```

NOTE: It's failing because of `sqlAdministratorLogin`. If `sqlAdministratorLogin` is changed to "adminwhatever", the call succeeds.

**Comment by MisinformedDNA** [comment]
@mikhailshilkov Is there a PR for this?

**Comment by mikhailshilkov** [comment]
Yes, this will be improved in the next release
