### ISSUE TITLE
Using not resolving

### ISSUE THREAD

**Issue by markjbrown** [pulumi/pulumi-azure-nextgen#22]
Using statements in VS 2019 do not properly resolve and I need to include the Package name to get items to compile/resolve correctly.

This does not work and you can see the AzureNextGen using statements are gray.

![using](https://user-images.githubusercontent.com/800166/94343622-2fe36900-ffce-11ea-8778-807bd72784cd.png)

So I'm required to do this.

![vs](https://user-images.githubusercontent.com/800166/94343630-425da280-ffce-11ea-9260-7c73c37e0027.png)

Which can result in really long statements like this.

![annoying](https://user-images.githubusercontent.com/800166/94343658-746f0480-ffce-11ea-99f0-367d465334ee.png)

**Comment by mikhailshilkov** [comment]
Hey @markjbrown thanks for opening the issue!

I believe that's how C# usings work. You have two options:

1. Import full module namespaces (and `Inputs` when needed) and then only refer to class names:

```cs
using Pulumi.AzureNextGen.DocumentDB.Latest;
using Pulumi.AzureNextGen.DocumentDB.Latest.Inputs;
//...
var databaseAccount = new DatabaseAccount("myaccount", new DatabaseAccountArgs
{
//...
});
```

2. Alias the namespace

```cs
using DocumentDB = Pulumi.AzureNextGen.DocumentDB.Latest;
//...
var databaseAccount = new DocumentDB.DatabaseAccount("myaccount", new DocumentDB.DatabaseAccountArgs
{
//...
});
```

Note that a simple `using Pulumi.AzureNextGen;` won't create an alias, so you can't refer to `AzureNextGen` in the code unless you do `using AzureNextGen = Pulumi.AzureNextGen;`

**Comment by markjbrown** [comment]
Hey @mikhailshilkov, nice to hear from you again.

I see. Ok, makes sense now. Still trying to get comfortable with your namespaces.

Thanks! you can close this.
