### ISSUE TITLE
Up on resources that fail due to error still ends up in state

### ISSUE THREAD

**Issue by WillooWisp** [pulumi/pulumi-azure-nextgen#221]
E.g. this EventHub resource still ends up in the stack's state and if I retry the up it thinks it is already created even though it failed in the previous and initial up.

```
error: autorest/azure: Service returned an error. Status=404 Code="ParentResourceNotFound" Message="Can not perform requested operation on nested resource. Parent resource 'TestSsd2323-EventHub' not found."
error: autorest/azure: Service returned an error. Status=404 Code="NotFound" Message="The namespace TestSsd2323-EventHub in subscription <id> is not active, its current state is Created. 
```

**Comment by mikhailshilkov** [comment]
Hi @WillooWisp Please provide more details about your code, the commands that you run, the output that you receive, and the state changes that you see. It's really hard to understand this issue right now.

**Comment by WillooWisp** [comment]
I have not been able to reproduce this, but I got in a state where the up of resources failed with errors from the provider service. Next time doing the state was not correct, since the resources where never added, but preview did not show them as something to add, so it seems the state thought they had already been added even if not.
