### ISSUE TITLE
Cannot pass outputs of storage account to ListStorageAccountKeys

### ISSUE THREAD

**Issue by reddyalready** [pulumi/pulumi-azure-nextgen#223]
I am creating a storage account and would subsequently like to list its keys, for which I am using https://www.pulumi.com/docs/reference/pkg/azure-nextgen/storage/liststorageaccountkeys/.

The above function only accepts inputs of type `string` however, and I need to provide the result of creating a storage account. Is there any way to do this that doesn't involve preserving the arguments to the storage account?

Thank you!

**Comment by mikhailshilkov** [comment]
Here is the pattern that you should use: https://github.com/pulumi/templates/blob/744f2d32eee0021558baf44536763fb27c63bc6d/azure-nextgen-typescript/index.ts#L23-L25

The ability to pass outputs directly is tracked in https://github.com/pulumi/pulumi/issues/5758 and https://github.com/pulumi/pulumi-azure-nextgen/issues/161

**Comment by mikhailshilkov** [comment]
Example for C# is here: https://github.com/pulumi/templates/blob/744f2d32eee0021558baf44536763fb27c63bc6d/azure-nextgen-csharp/MyStack.cs#L39

**Comment by reddyalready** [comment]
Stellar, that's worked wonderfully, thank you for your quick response 🙌
