### ISSUE TITLE
Docs are incorrect on DocumentDB index policy

### ISSUE THREAD

**Issue by markjbrown** [pulumi/pulumi-azure-nextgen#23]
The docs showing the index policy for [SqlResourceSqlContainer](https://www.pulumi.com/docs/reference/pkg/azure-nextgen/documentdb/sqlresourcesqlcontainer/) are incorrect. If used as shows without a composite index it will result in creating a v1 index policy which is being deprecated. This also includes a Spatial Index policy as an example.

Below is the correct way to create a v2 index for Cosmos DB container for SQL API.

![Capture](https://user-images.githubusercontent.com/800166/94343883-2bb84b00-ffd0-11ea-9b7d-41776eaa630b.JPG)

Apologies for the long resource names. Have another bug I'm dealing with.

**Comment by mikhailshilkov** [comment]
Hey @markjbrown 

The example that you refer to has been generated from [this JSON example](https://github.com/Azure/azure-rest-api-specs/blob/7d9eaf4c9866664806a2202b02e3ab5259c86cf9/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2020-04-01/examples/CosmosDBSqlContainerCreateUpdate.json) in Azure REST API Specifications repository. Do you think that example should be updated?

**Comment by markjbrown** [comment]
Yeah, I wondered if that's where you got it from.

I'll talk to my team about that. There's a ton of old cruft in there we need to update.

Thanks.

Closing.
