### ISSUE TITLE
The parameter accessPolicies is not specified

### ISSUE THREAD

**Issue by MisinformedDNA** [pulumi/pulumi-azure-nextgen#231]
The following code results in the error "The parameter accessPolicies is not specified":

```csharp
new AzureNextGen.KeyVault.V20180214.Vault("someappname-kv", new AzureNextGen.KeyVault.V20180214.VaultArgs
{
    Location = location,
    Properties = new AzureNextGen.KeyVault.V20180214.Inputs.VaultPropertiesArgs
    {
        AccessPolicies = {},
        EnabledForDeployment = false,
        EnabledForDiskEncryption = false,
        EnabledForTemplateDeployment = false,
        Sku = new AzureNextGen.KeyVault.V20180214.Inputs.SkuArgs
        {
            Family = "A",
            Name = "Standard",
        },
        TenantId = tenantId,
    },
    ResourceGroupName = resourceGroupNameParam,
    VaultName = "someappname-kv",
});
```

The ARM equivalent works fine

```json
{
  "type": "Microsoft.KeyVault/vaults",
  "apiVersion": "2018-02-14",
  "name": "someappname-kv",
  "location": "[resourceGroup().location]",
  "dependsOn": [],
  "properties": {
    "sku": {
      "family": "A",
      "name": "Standard"
    },
    "tenantId": "[subscription().tenantId]",
    "accessPolicies": [],
    "enabledForDeployment": false,
    "enabledForDiskEncryption": false,
    "enabledForTemplateDeployment": false
  }
}
```

The full ARM template is [here](https://github.com/Azure-Samples/KeyVault-Rotation-SQLPassword-Csharp/blob/main/ARM-Templates/Initial-Setup/azuredeploy.json).

**Comment by mikhailshilkov** [comment]
ARM templates have this funky feature to remove empty arrays automatically. I'm not sure we want to do the same. Does it work if you remove the `AccessPolicies` assignment?

**Comment by MisinformedDNA** [comment]
I haven't, but apparently [that fails](https://github.com/Azure/azure-resource-manager-schemas/issues/521) as well.

But as for the empty arrays, the ARM template executes fine. Are you referring to the REST API?

**Comment by mikhailshilkov** [comment]
Alright, I played with this a bit, and it's subtle.

**First**, `AccessPolicies = {},` is a no-op. The collection initializer syntax calls `Add` for every item in the specified collection. It does nothing for the empty specified collection. `AccessPolicies` is defined as

```cs
private InputList<AccessPolicyEntryArgs>? _accessPolicies;
public InputList<AccessPolicyEntryArgs> AccessPolicies
    {
      get => this._accessPolicies ?? (this._accessPolicies = new InputList<AccessPolicyEntryArgs>());
      set => this._accessPolicies = value;
    }
```

Neither getter nor setter is called in your code, so the list stays `null`.

If you want to initialize an empty list, you have to assign an explicit value:

```cs
AccessPolicies = new InputList<AzureNextGen.KeyVault.V20180214.Inputs.AccessPolicyEntryArgs>(),
```

**However**, this doesn't work either. This time it's a bug in our provider implementation when we inadvertently convert empty arrays to nulls. I found the culprit and will fix this behavior in the next version. I got the Key Vault created in my dev branch, so this explains the success of ARM templates.

Thank you for reporting.
