### ISSUE TITLE
SiteSourceControl does not exist in Latest

### ISSUE THREAD

**Issue by MisinformedDNA** [pulumi/pulumi-azure-nextgen#233]
`SiteSourceControl` exists in `V20150801`, but it does not exist in `Latest` (or any other version). However, it does exist in later versions of [the spec](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.Web/stable/2018-11-01/WebApps.json#L15038).

Why is it missing?

**Comment by mikhailshilkov** [comment]
It's called `WebAppSourceControl` https://www.pulumi.com/docs/reference/pkg/azure-nextgen/web/webappsourcecontrol/

**Comment by MisinformedDNA** [comment]
Ahh, because Azure changed the naming in the spec... sorry.
