### ISSUE TITLE
App Service Plan (and others) detecting diffs when upgrading AzureNextGen to 0.5.0

### ISSUE THREAD

**Issue by andrewdmoreno** [pulumi/pulumi-azure-nextgen#238]
I have a stack that has been in a stable state that is now detecting changes when upgrading to 0.5.0 of Pulumi.AzureNextGen from 0.4.0. 

The big problem here is that it is detecting a change to my **app service plan**. This is a problem because I have apps already deployed and running in this plan and thus `pulumi up` fails. I suspect this may have to do with the default properties enhancement, but deleting and recreating my app plan is not something I can do. 

````
    Type                             Name                        Operation
~   azure-nextgen:insights:Component component                   update
++  azure-nextgen:web:AppServicePlan AppServicePlan              create-replacement
++  azure-nextgen:web:WebAppSlot     MyApp-staging-slot          create-replacement
++  azure-nextgen:web:WebApp         MyApp                       create-replacement
~   azure-nextgen:keyvault:Vault     vault                       update


Sample Diff for plan:
```` json
{
    resourceGroup            : "MyRG" => Output<T>
    sku                      : {
        capabilities: Output<T>
        capacity    : 1 => Output<T>
        family      : "Pv2" => Output<T>
        locations   : Output<T>
        name        : "P1v2" => "P1V2"
        size        : "P1v2" => Output<T>
        skuCapacity : Output<T>
        tier        : "PremiumV2" => Output<T>
    }
    status                   : "Ready" => Output<T>
}
````

Is this expected, or am I doing something wrong? Any guidance would be appreciated.

**Comment by mikhailshilkov** [comment]
Does it show the reason for replacement? Could you show me your code so that I tried to reproduce it?

**Comment by andrewdmoreno** [comment]
@mikhailshilkov Can you guide me more specifically to the exact information you are to see in regards to reason for replacement? Do you mean this piece of the preview?

````
 +-  ├─ azure-nextgen:web/latest:AppServicePlan  AppServicePlan               replace     [diff: +hyperV,isXenon,perSiteScaling,reserved]
````

**Comment by andrewdmoreno** [comment]
Plan code:

```` c#
        private AppServicePlan CreateAppServicePlan()
        {
            var planSku = new SkuDescriptionArgs
            {
                Name = _config.Require("appServicePlanSku")
            };

            return new AppServicePlan("AppServicePlan",
                new AppServicePlanArgs
                {
                    Name = ResourceName("plan-grm"),
                    Location = _location,
                    ResourceGroupName = _resourceGroup,
                    Sku = planSku,
                });
        }
````

**Comment by andrewdmoreno** [comment]
Also, here is a screenshot of the diff if it helps:

![image](https://user-images.githubusercontent.com/2897853/105757301-cd6a8d00-5f1b-11eb-8758-da5ac655e1fb.png)

**Comment by mikhailshilkov** [comment]
Okay, I'm pretty sure that happens because `reserved` has changed from undefined to `false`, which is the default value as per the Azure API spec (and is now respected as per https://github.com/pulumi/pulumi-azure-nextgen/issues/183). We bumped to 0.5.0 because of this change.

A quick "fix" I can think of is to delete the app service plan from your state (the actual resource will remain in Azure) with `pulumi state delete <urn>` and import it again with `pulumi import azure-nextgen:web/latest:AppServicePlan AppServicePlan <id>`.

Is that good enough to unblock you for now.

**Comment by andrewdmoreno** [comment]
So, short answer: I think I can be unblocked in the short term just by setting the version in my .csproj to `0.4.0`. 

The longer answer is that my project was previously using version 0.* (hence why it broke on my deployment now). The previous deployment ran with v0.3.0 but I was running it again today in order to pick up the fixes for #185 that had been previously reported and fixed (thank you). After toying with it some I realized this breaking change was from `0.4.0` to `0.5.0`. 

I was reporting first and foremost to have a discussion as to whether this is a problem that was expected/should be fixed on the Pulumi end OR we will need to perform some kind of state fix as you suggested in the future in order to proceed with `0.5.0` or subsequent versions that may have bug fixes.

**Comment by mikhailshilkov** [comment]
The change in the state between the two versions was expected, the new state is meaningfully "better" (closer to the API spec). What we missed is that it would require a replacement for `AppServicePlan` (I think this may be the only resource type affected this way).

**Comment by andrewdmoreno** [comment]
I think I got it, let me repeat what I understood. The diff was expected to happen and should have been safe to update as it was in regards to default values, however, something was missed with `AppServicePlan` specifically that was **not** intended and should be fixed?

**Comment by mikhailshilkov** [comment]
Please try with 0.5.1

**Comment by andrewdmoreno** [comment]
Updated to 0.5.1 and ran a preview. AppServicePlan is now reflecting update instead of replace. Same with webapp.  

Slot, however, still says replace. Is this expected? 

Also, the key vault update is detecting a diff in the access policy assignment for the webapp with an empty guid object id. (This is using the `app.Identity.Apply(i => i?.PrincipalId ?? Guid.Empty.ToString())` workaround from #115 . This code has not changed between runs. Not sure if this is an ok diff.

```` json
[1]: {
      objectId   : "90xxxxx-xxxx-xxxx-xxxx-xxxxx6df" => "00000000-0000-0000-0000-000000000000"
````

![image](https://user-images.githubusercontent.com/2897853/105851349-f38e3c80-5fb0-11eb-9d8c-923ab5aa3b74.png)

Please let me know if any of these need to be separate issues and I can create them accordingly.

**Comment by mikhailshilkov** [comment]
> Slot, however, still says replace. Is this expected?

Which properties changed?

> (This is using the app.Identity.Apply(i => i?.PrincipalId ?? Guid.Empty.ToString()) workaround from #115 .

This workaround shouldn't be necessary anymore.

> Also, the key vault update is detecting a diff in the access policy assignment

That's because the web app has changed and the engine conservatively thinks that the identity may change as well. This will likely become a no-op during the actual update.

**Comment by andrewdmoreno** [comment]
> Which properties changed?

````
azure-nextgen:web/latest:WebAppSlot      staging-slot  replace     [diff: +hyperV,isXenon,reserved,scmSiteAlsoStopped~resourceGroupName,siteConfig]
````


> This workaround shouldn't be necessary anymore.

If I don't use the workaround I get the error in the first screenshot:
![image](https://user-images.githubusercontent.com/2897853/105854635-1f132600-5fb5-11eb-94e6-f22199e12c61.png)

**Comment by mikhailshilkov** [comment]
Could you please share your code for WebAppSlot?

**Comment by andrewdmoreno** [comment]
```` c#
        private (WebApp, WebAppSlot) CreateAppService(AppServicePlan plan, Component insights)
        {
            var siteConfigArgs = new SiteConfigArgs
            {
                AlwaysOn = true,
                AppSettings = new InputList<NameValuePairArgs>()
                {
                    AppSetting("KeyVaultUri", $"https://{_keyVaultName}.vault.azure.net/"),
                    AppSetting("WEBSITE_RUN_FROM_PACKAGE", "1"),
                    AppSetting("ASPNETCORE_ENVIRONMENT", _aspNetCoreEnvironment),
                    AppSetting("APPINSIGHTS_INSTRUMENTATIONKEY", insights.InstrumentationKey.Apply(key => key)),
                    AppSetting("APPLICATIONINSIGHTS_CONNECTION_STRING", insights.ConnectionString.Apply(conn => conn))
                }
            };

            var app = new WebApp("app", new WebAppArgs
            {
                Name = ResourceName("app-xxxxx"),
                Location = _location,
                ResourceGroupName = _resourceGroup,
                ServerFarmId = plan.Id,
                ClientAffinityEnabled = false,
                Identity = ManagedIdentity(),
                SiteConfig = siteConfigArgs,
                Tags = Tags,
                HttpsOnly = true
            });

            var slot = new WebAppSlot("app-staging-slot", new WebAppSlotArgs
            {
                Name = app.Name,
                Slot = "staging",
                Location = app.Location,
                ResourceGroupName = app.ResourceGroup,
                ServerFarmId = app.ServerFarmId!,
                Identity = ManagedIdentity(),
                SiteConfig = siteConfigArgs,
                Tags = Tags,
                HttpsOnly = true
            });

            return (app, slot);
        }
````

**Comment by mikhailshilkov** [comment]
It looks like it's unhappy about `resourceGroupName`. What if you set `ResourceGroupName = _resourceGroup`?

**Comment by andrewdmoreno** [comment]
Yes, that changed it to `update`. In general, should I have taken similar approach with other properties like `Name`, and `ServerFarmId` of not using the Outputs from the app and instead used `DependsOn` on `CustomResourceOptions`? Sorry if it's a silly question, still learning the best practices. 

```` c# 
            var slot = new WebAppSlot("staging-slot", new WebAppSlotArgs
            {
                Name = app.Name,
                Slot = "staging",
                // --------
            }, new CustomResourceOptions() { DependsOn = app});
````


Aside from that I did want to point out that the access policy assignment for the identity is still not happy though. Should I go back to the workaround?

````
azure-nextgen:keyvault/latest:Vault (vault):
    error: azure-nextgen:keyvault/latest:Vault resource 'vault' has a problem: missing required property 'properties.accessPolicies[1].objectId'
    error: azure-nextgen:keyvault/latest:Vault resource 'vault' has a problem: missing required property 'properties.accessPolicies[2].objectId'
````

**Comment by mikhailshilkov** [comment]
You should depend on "identifier" properties `Name` and `Id`, so these are good:

```
Name = app.Name,
ServerFarmId = plan.Id,
```

you can also rely on outputs that are the exact copy of inputs, like

```
ServerFarmId = app.ServerFarmId, // although I'd use plan.Id instead
```

`ResourceGroup` is an odd one: it's not the same as the `ResourceGroupName` input, so the engine isn't sure it won't change after an update.

> the access policy assignment for the identity is still not happy though. 

Yeah, I reopened that issue, please keep the workaround for now.

**Comment by andrewdmoreno** [comment]
Thanks for all your help. Really appreciated!
