### ISSUE TITLE
Unclear on how to create CompositeIndex with ImmutableArray

### ISSUE THREAD

**Issue by markjbrown** [pulumi/pulumi-azure-nextgen#24]
I'm trying to create a composite index in a Cosmos DB container index policy and I'm unclear how I would construct this inline with the container properties.

Is there an example for this?

![Capture](https://user-images.githubusercontent.com/800166/94345216-35927c00-ffd9-11ea-9c11-4752588a70d3.JPG)

Thanks.

**Comment by mikhailshilkov** [comment]
I think this is the simplest form:

```cs
var c = new SqlResourceSqlContainer("test", new SqlResourceSqlContainerArgs
{
    Resource = new SqlContainerResourceArgs
    {
        IndexingPolicy = new IndexingPolicyArgs
        {
            CompositeIndexes =
            {
                new[]
                {
                    new CompositePathArgs { Path = "myOrderByPath1", Order = "Ascending" },
                    new CompositePathArgs { Path = "myOrderByPath2", Order = "Ascending" },
                }.ToImmutableArray()
            }
        }
    }
});
```

**Comment by markjbrown** [comment]
Ah ok, cool. I'd not used this before.

Sorry for the 101 level C# question  :)
