### ISSUE TITLE
linux web apps require replace after upgrading from 0.4.0 to 0.5.1

### ISSUE THREAD

**Issue by orteme** [pulumi/pulumi-azure-nextgen#242]
linux web apps shows as to replace on preview:
![image](https://user-images.githubusercontent.com/51122404/105836749-52b27800-5fd6-11eb-951d-bd6cfdc6bc23.png)

function apps on windows looks better:
![image](https://user-images.githubusercontent.com/51122404/105836971-a91fb680-5fd6-11eb-8c39-d5492300f5e1.png)

I guess it can be related to #238

System info:
 - OS: Windows 10
 - pulumi: v2.18.2
 - template: azure-nextgen-csharp

**Comment by mikhailshilkov** [comment]
Do you set the value for the `reserved` property? I believe it should be `true` for Linux apps.

**Comment by orteme** [comment]
Yep, that's make sense. Replace is no more required after adding `reserved` property on web app level for linux apps. Thanks @mikhailshilkov!
