### ISSUE TITLE
Misssing Options parameter exception

### ISSUE THREAD

**Issue by markjbrown** [pulumi/pulumi-azure-nextgen#25]
I'm deploying a new Cosmos SqlDatabase resource and I get an exception that says I have to pass options.

Our resource provider does not require this so I'm confused why I'd have to pass this and what to pass.

Here's the exception.

System.ArgumentNullException: [Input] Pulumi.AzureNextGen.DocumentDB.Latest.DatabaseAccountSqlDatabaseArgs._options is required but was not given a value (Parameter '_options')
       at Pulumi.InputArgs.ToDictionaryAsync()
       at Pulumi.Deployment.PrepareResourceAsync(String label, Resource res, Boolean custom, ResourceArgs args, ResourceOptions options)
       at Pulumi.Deployment.RegisterResourceAsync(Resource resource, ResourceArgs args, ResourceOptions options)
       at Pulumi.Deployment.ReadOrRegisterResourceAsync(Resource resource, ResourceArgs args, ResourceOptions options)
       at Pulumi.Deployment.CompleteResourceAsync(Resource resource, ResourceArgs args, ResourceOptions options, ImmutableDictionary`2 completionSources)
       at Pulumi.Deployment.Runner.<>c__DisplayClass7_0.<<WhileRunningAsync>g__HandleCompletion|0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at Pulumi.Deployment.Runner.WhileRunningAsync()

**Comment by mikhailshilkov** [comment]
I believe you can pass it simply as

```cs
Options = new CreateUpdateOptionsArgs(),
```

I do not know why but `options` seems to be marked as required in the spec: https://github.com/Azure/azure-rest-api-specs/blob/7d9eaf4c9866664806a2202b02e3ab5259c86cf9/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2020-04-01/cosmos-db.json#L6379

**Comment by markjbrown** [comment]
That's weird. When I call our control plane API say via our .NET RP SDK I can ignore it completely so not sure how that is happening since our generated SDK's are made from the same swagger spec. Thanks for point it out. I'll talk to my team.

Thanks again!

**Comment by markjbrown** [comment]
I get a conversion error when I use that suggestion.

![Capture](https://user-images.githubusercontent.com/800166/94351612-abb1d580-000f-11eb-93b6-90737a6bb274.JPG)

**Comment by mikhailshilkov** [comment]
You don't show it on your screenshot but I think you were trying to create a `DatabaseAccountSqlDatabase` while I gave you an answer for `SqlResourceSqlDatabase`. 

`DatabaseAccountSqlDatabase` is an older resource (version 2016-03-01) and models options as an untyped map. So you can do:

```cs
var sql = new DatabaseAccountSqlDatabase("sadas", new DatabaseAccountSqlDatabaseArgs
{
    //...
    Options =
    {
    }
});
```

Although, you likely want to use `SqlResourceSqlDatabase` instead.

Now, I opened a separate issue asking why there are _both_ these resources in the `Latest` version. @markjbrown I'd appreciate your feedback in https://github.com/pulumi/pulumi-azure-nextgen/issues/26

**Comment by markjbrown** [comment]
I responded to #26. I hope my explanation makes sense. The evolution of our management api has not been a straight line unfortunately.

I changed my database and container resources to the correct types you suggest above. However I still get the same error for the database resource which I am not specifying throughput.

![Capture](https://user-images.githubusercontent.com/800166/94369452-99cb4380-009e-11eb-9770-f2e852cc8b99.JPG)

**Comment by mikhailshilkov** [comment]
I don't think it's related, but we had another bug in the same `SqlResourceSqlDatabase` resource. Could you please upgrade to the latest dev build. Install it with:

```
pulumi plugin install resource azure-nextgen v0.1.1-alpha.1601196036+2e0c945a
```

and then update your NuGet package in `csproj`:

```
<PackageReference Include="Pulumi.AzureNextGen" Version="0.1.1-alpha.1601196036" />
```

WIth this, the following code deploys fine for me:

```cs
var sqlDatabase = new SqlResourceSqlDatabase("sqlDatabase", new SqlResourceSqlDatabaseArgs
{
    AccountName = databaseAccount.Name,
    DatabaseName = "mydbcs",
    Location = resourceGroup.Location,
    Resource = new SqlDatabaseResourceArgs
    {
        Id = "mydbcs",
    },
    Options = new CreateUpdateOptionsArgs(),
    ResourceGroupName = resourceGroup.Name,
});
```

**Comment by mikhailshilkov** [comment]
For completeness, my account:

```cs
var databaseAccount = new DatabaseAccount("databaseAccount", new DatabaseAccountArgs
{
    AccountName = "mycosmos",
    Capabilities = 
    {
        new CapabilityArgs { Name = "EnableServerless" }
    },
    DatabaseAccountOfferType = "Standard",
    Location = resourceGroup.Location,
    Locations = 
    {
        new LocationArgs
        {
            FailoverPriority = 0,
            LocationName = resourceGroup.Location
        },
    },
    ResourceGroupName = resourceGroup.Name,
});
```

**Comment by markjbrown** [comment]
Updated but still get same error :(

**Comment by markjbrown** [comment]
Ok, got an error on the container. A very long error :)

Diagnostics:
  pulumi:pulumi:Stack (quickstart-dev):
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xc0000005 code=0x0 addr=0x50 pc=0xda8ac0]
    goroutine 56 [running]:
    github.com/pulumi/pulumi-azure-nextgen-provider/provider/pkg/provider.(*azureNextGenProvider).validateProperty(0xc00654c4b0, 0xc008986a20, 0x2e, 0x0, 0xe9d120, 0xc002741aa0, 0x2e, 0x0, 0x6400000001)
        /home/runner/work/pulumi-azure-nextgen-provider/pulumi-azure-nextgen-provider/provider/pkg/provider/provider.go:324 +0x14b0
    github.com/pulumi/pulumi-azure-nextgen-provider/provider/pkg/provider.(*azureNextGenProvider).validateProperty(0xc00654c4b0, 0xc0089869f0, 0x2b, 0xc00537f740, 0xe37700, 0xc007b8c0c0, 0x2b, 0xc0053592c0, 0x10)
        /home/runner/work/pulumi-azure-nextgen-provider/pulumi-azure-nextgen-provider/provider/pkg/provider/provider.go:343 +0x280
    github.com/pulumi/pulumi-azure-nextgen-provider/provider/pkg/provider.(*azureNextGenProvider).validateProperty(0xc00654c4b0, 0xc008986990, 0x28, 0xc00275e708, 0xe37700, 0xc007b8c0e0, 0x28, 0x0, 0x0)
        /home/runner/work/pulumi-azure-nextgen-provider/pulumi-azure-nextgen-provider/provider/pkg/provider/provider.go:343 +0x280
    github.com/pulumi/pulumi-azure-nextgen-provider/provider/pkg/provider.(*azureNextGenProvider).validateType(0xc00654c4b0, 0xc006e47e60, 0x17, 0xc00275ea20, 0xc002741a70, 0x50163a, 0xc007c54680, 0xc005359632)
        /home/runner/work/pulumi-azure-nextgen-provider/pulumi-azure-nextgen-provider/provider/pkg/provider/provider.go:305 +0x3a0
    github.com/pulumi/pulumi-azure-nextgen-provider/provider/pkg/provider.(*azureNextGenProvider).validateProperty(0xc00654c4b0, 0xc006e47e60, 0x17, 0xc00275ed98, 0xe9d120, 0xc002741a70, 0x17, 0x0, 0x0)
        /home/runner/work/pulumi-azure-nextgen-provider/pulumi-azure-nextgen-provider/provider/pkg/provider/provider.go:332 +0x15a6
    github.com/pulumi/pulumi-azure-nextgen-provider/provider/pkg/provider.(*azureNextGenProvider).validateType(0xc00654c4b0, 0xc007ad2ff0, 0x8, 0xc00275f0b0, 0xc002741a40, 0x0, 0x0, 0x0)
        /home/runner/work/pulumi-azure-nextgen-provider/pulumi-azure-nextgen-provider/provider/pkg/provider/provider.go:305 +0x3a0
    github.com/pulumi/pulumi-azure-nextgen-provider/provider/pkg/provider.(*azureNextGenProvider).validateProperty(0xc00654c4b0, 0xc007ad2ff0, 0x8, 0xc00275f428, 0xe9d120, 0xc002741a40, 0x0, 0x0, 0x0)
        /home/runner/work/pulumi-azure-nextgen-provider/pulumi-azure-nextgen-provider/provider/pkg/provider/provider.go:332 +0x15a6
    github.com/pulumi/pulumi-azure-nextgen-provider/provider/pkg/provider.(*azureNextGenProvider).validateType(0xc00654c4b0, 0x0, 0x0, 0xc007ac5c80, 0xc0027419b0, 0x0, 0x0, 0x0)
        /home/runner/work/pulumi-azure-nextgen-provider/pulumi-azure-nextgen-provider/provider/pkg/provider/provider.go:305 +0x3a0
    github.com/pulumi/pulumi-azure-nextgen-provider/provider/pkg/provider.(*azureNextGenProvider).Check(0xc00654c4b0, 0x11948c0, 0xc002741170, 0xc00274a2c0, 0xc00654c4b0, 0xea4601, 0xc00274b080)
        /home/runner/work/pulumi-azure-nextgen-provider/pulumi-azure-nextgen-provider/provider/pkg/provider/provider.go:246 +0x9ef
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Check_Handler.func1(0x11948c0, 0xc002741170, 0xf70420, 0xc00274a2c0, 0xf88740, 0x1e0cf00, 0x11948c0, 0xc002741170)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.10.2-0.20200920185652-988ebd8b8e6f/proto/go/provider.pb.go:2181 +0x8d
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x11948c0, 0xc002740c30, 0xf70420, 0xc00274a2c0, 0xc007cbefe0, 0xc007cbf000, 0x0, 0x0, 0x117af00, 0xc000336790)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2f2
    github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Check_Handler(0xfba380, 0xc00654c4b0, 0x11948c0, 0xc002740c30, 0xc00664d320, 0xc000262420, 0x11948c0, 0xc002740c30, 0xc0002f5000, 0x3d7)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.10.2-0.20200920185652-988ebd8b8e6f/proto/go/provider.pb.go:2183 +0x152
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc00010e000, 0x119eb60, 0xc000594180, 0xc0000f2900, 0xc00b5d65a0, 0x1dcfbf8, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1082 +0x511
    google.golang.org/grpc.(*Server).handleStream(0xc00010e000, 0x119eb60, 0xc000594180, 0xc0000f2900, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1405 +0xcd4
    google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0007168b0, 0xc00010e000, 0x119eb60, 0xc000594180, 0xc0000f2900)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0xa8
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xa8

  azure-nextgen:documentdb:SqlResourceSqlContainer (container1):
    error: transport is closing

**Comment by mikhailshilkov** [comment]
@markjbrown This looks like our validation is failing for one of those properties.
Could you copy-paste this snippet here or to a gist? Thank you!

**Comment by markjbrown** [comment]
Sure. Here is the entire class.

https://gist.github.com/markjbrown/08d165dc15870bce0c4c92362ada3424

**Comment by mikhailshilkov** [comment]
Something fishy is going on with `CompositeIndexes` processing on our side. Opened https://github.com/pulumi/pulumi-azure-nextgen/issues/28 - I'll fix it tomorrow.

For now, avoid using this property if possible.

Thank you!

**Comment by markjbrown** [comment]
Looks like that fixed it.

Got a question though.

Why does Pulumi create resources with numbers appended? This would mean that if I want to modify my deployment I would have to modify the resource names to match Pulumi deployed. Also, what if I don't want these appended numbers. How could Pulumi adapt to that?

Thanks.

**Comment by markjbrown** [comment]
ok, spoke too soon. Got this error during deployment.

View Live: https://app.pulumi.com/markjbrown/quickstart/dev/updates/2

     Type                                         Name               Status                  Info
     pulumi:pulumi:Stack                          quickstart-dev     **failed**              1 error
 +   ├─ azure-nextgen:resources:ResourceGroup     mjbPulumi          created
 +   └─ azure-nextgen:documentdb:DatabaseAccount  mjbPulumi-Account  **creating failed**     1 error

Diagnostics:
  pulumi:pulumi:Stack (quickstart-dev):
    error: update failed

  azure-nextgen:documentdb:DatabaseAccount (mjbPulumi-Account):
    error: Code="ResourceGroupNotFound" Message="Resource group 'mjbPulumi2' could not be found."

Outputs:
    ConnectionString: "DefaultEndpointsProtocol=https;AccountName=mjbstorage5e4723ec;AccountKey=[redacted];EndpointSuffix=core.windows.net"

Resources:
    + 1 created
    1 unchanged

Duration: 9s

**Comment by mikhailshilkov** [comment]
> Why does Pulumi create resources with numbers appended? 

That was true for the old provider, but the new ("Next Gen") does not append anything to resource names that you specify. If you say `AccountName = "myaccount"` you should get the Azure resource `myaccount`.

Or what do you mean here?

**Comment by markjbrown** [comment]
Yeah that was it. I see now in this deployment not appending numbers. This is perfect.

Deploying now.

Got another question. Why does intellisense in VS show autocomplete for parameters as Input<string>, InputMap<T>, etc? Is this some artifact from your code gen process?

**Comment by mikhailshilkov** [comment]
> Why does intellisense in VS show autocomplete for parameters as Input, InputMap, etc? Is this some artifact from your code gen process?

Yes, these are our generic types that codegen assigns. Basically, this is to allow floating output values from one resource to inputs of another one.

For example, I defined a database account args above with `Location = resourceGroup.Location,`. In this case, `Location` is an `Input<string>` and `resourceGroup.Location` is an `Output<string>`. Outputs may not be immediately known because they are the values that we get from Azure while creating resources. `Output`/`Input` type system enables that. You can read more in our [Programming Model](https://www.pulumi.com/docs/intro/concepts/programming-model/#outputs) docs.

Ideally, we would ship a custom extension for Visual Studio, that would ignore the `Input` types and would suggest the specific argument types. It could also do things like highlighting missing required properties. But we aren't there yet.

**Comment by markjbrown** [comment]
ok, makes sense. Thanks Mikhail. Let me know when you have a fix for composite index.

**Comment by mikhailshilkov** [comment]
Closing this issue as the composite index problem is tracked separately
