### ISSUE TITLE
Cannot create Azure SQL Database with AzureNext but it works with "old" azure

### ISSUE THREAD

**Issue by rchamorro** [pulumi/pulumi-azure-nextgen#251]
When I try to create a database with AzureNextGen provider it is able to preview but update fails with this error:

> error: Code="ResourceGroupNotFound" Message="Resource group 'name-of-resourcegroup' could not be found."

```csharp
var dbNextGen = new Pulumi.AzureNextGen.Sql.Latest.Database("db", new DatabaseArgs
        {
            DatabaseName = "db-name",
            ServerName = sqlServer.Name,
            Location = "westeurope",
            ResourceGroupName = "name-of-resource-group",
            Edition = "Standard",
            MaxSizeBytes = 2147483648,
            RequestedServiceObjectiveName = config.Require("dbServiceTier"),
        });
```
If I try to create it with the old provider it works perfectly :

```csharp
var dbOld = new Pulumi.Azure.Sql.Database("db", new Pulumi.Azure.Sql.DatabaseArgs
        {
            Name = "db-name",,
            ServerName = sqlServer.Name,
            Location = "westeurope",
            ResourceGroupName = "name-of-resource-group",
            Edition = "Standard",         
            MaxSizeBytes = 2147483648,
            RequestedServiceObjectiveName = config.Require("dbServiceTier"),
        });
```

Other data:
- Pulumi cli version: v2.19.0
- Pulumi.AzureNextGen nuget: 0.5.1
- Pulumi.Azure nuget: 3.44.0

**Comment by mikhailshilkov** [comment]
This is unexpected... We have a test in our CI that creates a SQL database on every PR and it never fails like this. Do you have a standalone program for me to repro this? I can share ours but it's in TypeScript.

**Comment by mikhailshilkov** [comment]
As I haven't heard back and we have a test that checks this resource, I'll go ahead and close the issue. Feel free to reopen with a full repro.
