### ISSUE TITLE
Container Registry Tasks Not Supporting Steps

### ISSUE THREAD

**Issue by JasonWhall** [pulumi/pulumi-azure-nextgen#256]
Hi, Currently the Container Registry Task Resource only supports a base class called [TaskStepPropertiesArgs](https://www.pulumi.com/docs/reference/pkg/azure-nextgen/containerregistry/task/#taskstepproperties) in the [step](https://www.pulumi.com/docs/reference/pkg/azure-nextgen/containerregistry/task/#step_csharp) property. It looks like it is missing supporting the 3 different options in this property for all languages:
- [DockerBuildStep](https://docs.microsoft.com/en-us/rest/api/containerregistry/tasks/create#dockerbuildstep)
- [FileTaskStep](https://docs.microsoft.com/en-us/rest/api/containerregistry/tasks/create#filetaskstep)
- [EncodedTaskStep](https://docs.microsoft.com/en-us/rest/api/containerregistry/tasks/create#encodedtaskstep)

These are all listed as a supported option in the REST API [here](https://docs.microsoft.com/en-us/rest/api/containerregistry/tasks/create#request-body) and seem to only be available as outputs only on the AzureNextGen provider.

**Comment by mikhailshilkov** [comment]
Hi, thank you, this is interesting.

The `type` property of `TaskStepProperties` is marked as read-only in the API specs: https://github.com/Azure/azure-rest-api-specs/blob/0c90247ad2604b12457a43e7613bc07c709795ad/specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/stable/2019-04-01/containerregistry_build.json#L1287

Therefore, we assume the SDK can't set it, so we don't generate the derived types either. They are useless without setting the `type` property.

Now, the question is whether a) we misinterpret something b) the specs are wrong, or c) this property is indeed read-only.

**Comment by mikhailshilkov** [comment]
It looks like they fixed this in `2019-06-01-preview` - try using this version instead of `latest`.

**Comment by JasonWhall** [comment]
Apologies, yes this is working in `2019-06-01-preview` and all options are available. Thanks, will close this issue!
