### ISSUE TITLE
Import SQL Managed Instance fails to parse id

### ISSUE THREAD

**Issue by flytzen** [pulumi/pulumi-azure-nextgen#280]
Trying to import an existing Azure SQL Managed instance with the following code:
```
const managedSqlInstance = new azure.sql.v20200801preview.ManagedInstance("fl-vnettest-sm", {
<snip>
    },
    {
        import: "subscriptions/33XXX35d/resourceGroups/fl-vnettest/providers/Microsoft.Sql/managedInstances/fl-vnettest-sm"
    });
```

I get this error (subscription id replaced for safety:
```
  azure-nextgen:sql/v20200801preview:ManagedInstance (fl-vnettest-sm):
    error: Preview failed: failed to parse 'subscriptions/XXXX/resourceGroups/fl-vnettest/providers/Microsoft.Sql/managedInstances/fl-vnettest-sm' against the 
path '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/managedInstances/{managedInstanceName}'
```

NOTE: The managed instance was actually created by Pulumi. But it's a very long-running operation so my machine was interrupted before it finished. On the next "pulumi up", I got the message that there was a pending operation and followed the advice to remove the "pending operation" from the state. Unfortunately, this led to Pulumi thinking the resource doesn't exist, hence why I am now trying to import it :D

PS: I'd love to help by writing a PR for this. What's the best way to get started? I believe a lot of the code is generated so I don't know if we need to change a generator?

**Comment by mikhailshilkov** [comment]
You import ID should start with a `/`: `/subscriptions/33XXX35d/resourceGroups/fl-v...`

**Comment by mikhailshilkov** [comment]
By the way, you can also use the import CLI command as shown in https://www.pulumi.com/docs/reference/pkg/azure-nextgen/sql/managedinstance/#import
(you still need to get the ID right)

**Comment by flytzen** [comment]
Doh!! Sorry, I thought I had checked that properly. And thank you for the link.
