### ISSUE TITLE
WebApplicationSettings is incorrectly named

### ISSUE THREAD

**Issue by MisinformedDNA** [pulumi/pulumi-azure-nextgen#282]
`WebApplicationSettings` get mapped from [WebApps_UpdateApplicationSettings](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.Web/stable/2020-10-01/WebApps.json#L1012), but it does not follow the naming convention.

`WebApplicationSettings` should be `WebAppApplicationSettings`

**Comment by mikhailshilkov** [comment]
We'll rename it in 0.7.0
