### ISSUE TITLE
Subnets break after refresh

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi-azure-nextgen#283]
Found an interesting issue today - we created a VNet with 2 subnets defined as separate resources. This deployed fine.

We then ran a Pulumi refresh for a separate reason.

The next deploy we ran failed because it was trying to delete subnets from within the VNet resource.

It appears the refresh had made the VNet resource adopt the subnets as a property rather than keeping them as separate resources. Then when trying to deploy again it attempts to delete the subnets within the VNet as they're not there in the code.

**Comment by mikhailshilkov** [comment]
Is this the same as https://github.com/pulumi/pulumi-azure-nextgen/issues/103 ?

**Comment by danielrbradley** [comment]
> Is this the same as https://github.com/pulumi/pulumi-azure-nextgen/issues/103 ?

Ah yup, think that's the same root issue. Feel free to close as a duplicate 👍
