### ISSUE TITLE
Import of existing KeyVault not possible due to case-sensitive state comparison

### ISSUE THREAD

**Issue by sebbegg** [pulumi/pulumi-azure-nextgen#294]
I would like to import an existing KeyVault into our stack. That does not seem to be possible though, as I can't seem to get matching states.
After aligning all other properties, I'm stuck with one diff in the preview:

```
  ~ properties: {
      ~ sku: {
          ~ name: "Standard" => "standard"
        }
    }
```
I cannot seem to work around this, since using `SkuArgs` with a lower-case `standard` produces:

```
error: azure-nextgen:keyvault/latest:Vault resource 'xyz' has a problem: 'properties.sku.name' is 'Standard' but expected one of ['standard','premium']
```

I noticed the case-sensisitivy issue with the `PermissionsArgs` too, but in this case there doesn't seem to be a constraint to lower-case on pulumi-side.
Any way to work around this for the `Sku` argument too?

## Expected behavior
Comparisons on properties where case is treated different in Pulumi and on Azure should probably be handled case-insensitively.

## Current behavior
See above.

## Steps to reproduce
I expect this should be reproducible by creating any KeyVault e.g. in the Azure Portal and trying to import that.

**Comment by mikhailshilkov** [comment]
Sorry for the inconvenience. Two options to try:

1. Add `properties.sku.name` to the `ignoreChanges` option of the resource.
2. Use the import command `pulumi import azure-nextgen:keyvault/latest:Vault sample-vault <your-keyvault-id>`

Meanwhile, we'll see what we can do about the validation.

**Comment by sebbegg** [comment]
Thank you for the quick reply, both options in the end still fail because of the `standard` vs `Standard` issue:

```
error: azure-nextgen:keyvault/latest:Vault resource 'sample-vault' has a problem: 'properties.sku.name' is 'Standard' but expected one of ['standard','premium']
```

**Comment by mikhailshilkov** [comment]
I see... I guess we'll have to relax our internal check.

**Comment by mikhailshilkov** [comment]
The check will be relaxed in 0.7.0
