### ISSUE TITLE
Internal Server Error when Adding Key Value to Azure App Configuration using Pulumi

### ISSUE THREAD

**Issue by jizzaki** [pulumi/pulumi-azure-nextgen#298]
I have a simple stack that creates an Azure App Configuration and adds a Key Value. This was working a few days ago and I'm not sure what happened but it's no longer working. I have full admin rights on these azure tenants and I've tested it against multiple subscriptions.

## Expected behavior

Key Value should be Created.

## Current behavior

```
Diagnostics:
  azure-nextgen:appconfiguration/v20200701preview:KeyValue (tester$123):
    error: cannot check existence of resource '/subscriptions/[subscriptionId]/resourceGroups/test-delete-rg/providers/Microsoft.AppConfiguration/configurationStores/test-delete-appconfig123456/keyValues/tester%24123': status code 500, {"error":{"code":"InternalServerError","message":"Cannot serve the request. Please retry.","additionalInfo":[{"type":"ActivityId","info":{"activityId":"787f2f98-cde5-423c-8d19-6a3ed145179d"}}]}}

  pulumi:pulumi:Stack (CSharpTest-dev):
    warning: provider config warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider
    error: update failed
```

## Steps to reproduce
```
class MyStack : Stack
{
    public MyStack()
    {
        // Create an Azure Resource Group

        var resourceGroup = new Pulumi.Azure.Core.ResourceGroup("test-delete-rg", new ResourceGroupArgs
        {
            Location = "westus 2",

            Name = "test-delete-rg"
        });

        Output.All(resourceGroup.Name).Apply((input) =>
        {
            var resourceGroupName = input[0];

            var configurationStore = new Pulumi.AzureNextGen.AppConfiguration.Latest.ConfigurationStore("test-delete-appconfig123456",
             new Pulumi.AzureNextGen.AppConfiguration.Latest.ConfigurationStoreArgs
             {
                 ConfigStoreName = "test-delete-appconfig123456",
                 ResourceGroupName = resourceGroupName,
                 Location = "westus 2",
                 Sku = new Pulumi.AzureNextGen.AppConfiguration.Latest.Inputs.SkuArgs
                 {
                     Name = "Standard",
                 }
             }, new CustomResourceOptions
             {
                 DeleteBeforeReplace = true
             });


            var keyValue = new Pulumi.AzureNextGen.AppConfiguration.V20200701Preview.KeyValue($"tester$123",
             new Pulumi.AzureNextGen.AppConfiguration.V20200701Preview.KeyValueArgs
             {
                 ConfigStoreName = configurationStore.Name,
                 KeyValueName = $"tester$123",
                 ResourceGroupName = resourceGroupName,
                 Value = "somevalue123",
             }, new CustomResourceOptions { DeleteBeforeReplace = true });

            OutputCreateKeyValue = keyValue.Name;

            return keyValue.Name;
        });

    }

    [Output]
    public Output<string> OutputCreateKeyValue { get; set; }
}

```

I've also tried the above **without** the Output.All since the ResourceGroup.Name is also an Output. That **does not work** as well.

**Comment by jizzaki** [comment]
In addition to this I've tried many custom resource options to hack at it, without any luck. I suspect it has to do with the Azure API but I'm not completely certain.

**Comment by mikhailshilkov** [comment]
`Output.All` isn't needed indeed.

Are you getting the same error for keys that don't have a `$` in them? Could you check Azure logs for activity `787f2f98-cde5-423c-8d19-6a3ed145179d` or contact support to understand the reason for 500?

**Comment by jizzaki** [comment]
Yes, I mentioned that I've tried both with and without `Output.All`, neither work. A couple of days ago I was able to create an Azure App Configuration with 50+ keys using any combination of Keys with `$` and without. Today it won't create any. Instead, it takes approximately 8 minutes before it decides to fail and return an error message.

Here's the latest failure attempt creating a Key Value **without** the `$`
```

View Live: https://app.pulumi.com/jizzaki/CSharpTest/dev/previews/..

     Type                                                         Name            Plan       Info
     pulumi:pulumi:Stack                                          CSharpTest-dev             1 warning
 +   └─ azure-nextgen:appconfiguration/v20200701preview:KeyValue  keyvalue        create
 
Diagnostics:
  pulumi:pulumi:Stack (CSharpTest-dev):
    warning: provider config warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider

Outputs:
  + OutputCreateKeyValue: output<string>


Do you want to perform this update? yes
Updating (dev)

View Live: https://app.pulumi.com/jizzaki/CSharpTest/dev/updates/6

     Type                                                         Name            Status                  Info
     pulumi:pulumi:Stack                                          CSharpTest-dev  **failed**              1 error; 1 warning
 +   └─ azure-nextgen:appconfiguration/v20200701preview:KeyValue  keyvalue        **creating failed**     1 error
 
Diagnostics:
  pulumi:pulumi:Stack (CSharpTest-dev):
    warning: provider config warning: "skip_credentials_validation": [DEPRECATED] This field is deprecated and will be removed in version 3.0 of the Azure Provider
    error: update failed

  azure-nextgen:appconfiguration/v20200701preview:KeyValue (keyvalue):
    error: cannot check existence of resource '/subscriptions/[subscriptionId]/resourceGroups/test-delete-rg/providers/Microsoft.AppConfiguration/configurationStores/test-delete-appconfig123456/keyValues/keyvalue': status code 500, {"error":{"code":"InternalServerError","message":"Cannot serve the request. Please retry.","additionalInfo":[{"type":"ActivityId","info":{"activityId":"4403d15a-5124-45f4-870b-ee9e6ad8b24d"}}]}}

Resources:
    3 unchanged

Duration: 7m41s


```

**Comment by mikhailshilkov** [comment]
It looks like an Azure service issue to me. Please contact Azure support.

**Comment by jizzaki** [comment]
> It looks like an Azure service issue to me. Please contact Azure support.

Were you able to replicate? Or have you determined this is an issue with only my account?

**Comment by mikhailshilkov** [comment]
Yes, I get the same error. The portal shows this:

![image](https://user-images.githubusercontent.com/1454008/108478806-3df39800-7295-11eb-95c2-f75e9977b8c1.png)

**Comment by jizzaki** [comment]
Thank you, I've notified Azure services.

**Comment by jizzaki** [comment]
> Yes, I get the same error. The portal shows this:
> 
> ![image](https://user-images.githubusercontent.com/1454008/108478806-3df39800-7295-11eb-95c2-f75e9977b8c1.png)

If you dont mind, how were you able to replicate this from the portal?

**Comment by mikhailshilkov** [comment]
I did not replicate - I went to the activity log of the App Configuration and located the error there

**Comment by jizzaki** [comment]
> I did not replicate - I went to the activity log of the App Configuration and located the error there

I posted this bug on Azure's github and they replied saying that its a regression the error message should actually be a 404 (resource not found).

What I dont understand is why would the resource not be found if the goal is to create the Key Value? Is there a bug with how the key value is first being looked up?

![image](https://user-images.githubusercontent.com/11037600/108548305-849abf80-72a0-11eb-8641-4c515685732e.png)

Azure bug github reference
https://github.com/Azure/AppConfiguration/issues/466

**Comment by mikhailshilkov** [comment]
404 would be perfect and Pulumi would continue with the resource creation. This is a pre-check that we do to avoid accidental overrides of existing unmanaged resources.

**Comment by jizzaki** [comment]
Gotcha. Thank you so much!
