### ISSUE TITLE
Provider ignores provider settings from stack configuration

### ISSUE THREAD

**Issue by bantoni** [pulumi/pulumi-azure-nextgen#33]
Hi,

I tried to set the Azure Tenant Id and Subscription Id which should be used by the provider in the stack configuration:
```
config:
  azure-nextgen:subscriptionId: ***
  azure-nextgen:tenantId: ***
```
The values are not used by the nextgen provider v0.1.0. Instead, I get the following error:
```
    error: building auth config: 2 errors occurred:
    	* A Subscription ID must be configured when authenticating as a Service Principal using a Client Secret.
    	* A Tenant ID must be configured when authenticating as a Service Principal using a Client Secret.
```
 
Setting the two config values as environment variable works as expected:
```
  $env:ARM_TENANT_ID="***"
  $env:ARM_SUBSCRIPTION_ID="***"
```

**Comment by mikhailshilkov** [comment]
Hi @bantoni thank you for opening the issue, sorry takes a bit long to respond.

I tried the following configuration in `Pulumi.dev.yaml`:

```
config:  
  azure-nextgen:clientId: <guid>
  azure-nextgen:clientSecret:
    secure: AAABAIcfxDQ4q7HsDdB5o/JjguC4mviLvTiadZ3Fjm1esuPJe9Iwgord56ioK6Dp5rwxFScok4OFovPxLSFLsMlK
  azure-nextgen:subscriptionId: <guid>
  azure-nextgen:tenantId: <guid>
```

and the values are read correctly for me. Do you know what may be the difference between our setups?

**Comment by bantoni** [comment]
In my setup, I just configured the subscription id and tenant id in the configuration. The client id and secret is set as environment variable. Maybe this causes the issue?

**Comment by mikhailshilkov** [comment]
This still works for me...

Any chance you are using the `azure` provider side-by-side with `azure-nextgen` and something isn't configured there?

**Comment by mikhailshilkov** [comment]
No, I think the error message belongs to the `azure-nextgen`. That's odd.

Could you run `pulumi up --skip-preview --yes -v=9 --logtostderr` and search for `Configure()` in the output? Are all the values set there?

**Comment by bantoni** [comment]
Now the error disappeared. I don't know why.
I close this issue. If the error comes back for whatever reason, I'll have a look at the debug output.
Thanks.
