### ISSUE TITLE
Can't list appsettings of the Function App

### ISSUE THREAD

**Issue by PawelStadnicki** [pulumi/pulumi-azure-nextgen#41]
No matter method  I try I cannot list the configuration (App settings) of function app.
Function app is on App Service Plan and for example I just want to read the 
connection string. 

It should be simple.

I also tried method ListWebApplicationSettings but it only return the resource name called "AppSetting" and I have no idea what to do next with it

**Comment by mikhailshilkov** [comment]
Thank you for reporting this!

Connection strings in particular should be returned from [ListWebAppConnectionStrings](https://www.pulumi.com/docs/reference/pkg/azure-nextgen/web/listwebappconnectionstrings/) but, as you see in the docs, we are missing the actual values in the return type. I will investigate.

**Comment by PawelStadnicki** [comment]
> Thank you for reporting this!
> 
> Connection strings in particular should be returned from [ListWebAppConnectionStrings](https://www.pulumi.com/docs/reference/pkg/azure-nextgen/web/listwebappconnectionstrings/) but, as you see in the docs, we are missing the actual values in the return type. I will investigate.

Thanks. I guess the reason will be the same as for ListWebApplicationSettings
