### ISSUE TITLE
ID retrieval for Vnet

### ISSUE THREAD

**Issue by alan0609** [pulumi/pulumi-azure-nextgen#48]
I can't see a way to retrieve the ID of a Vnet from the name and resource group.  Is this possible in nextgen?

**Comment by mikhailshilkov** [comment]
It looks like we are missing `id` in the invocation result types, e.g. in https://github.com/pulumi/pulumi-azure-nextgen/blob/9086bdba5e490fd771109aebaf6b792154977621/sdk/nodejs/network/latest/getVirtualNetwork.ts#L42

**Comment by MerelyAPseudonym** [comment]
@mikhailshilkov You might already be aware of this, but other results also lack a resource ID. For example: https://github.com/pulumi/pulumi-azure-nextgen/blob/d15f700c73e33f5d7dbedc64259958c9f0bd3c0e/sdk/nodejs/resources/v20200601/getResourceGroup.ts#L29-L57

**Comment by mikhailshilkov** [comment]
This issue is fixed in 0.3.0
