### ISSUE TITLE
Different IP Configuration parameters from pulumi-azure

### ISSUE THREAD

**Issue by jamesianberry** [pulumi/pulumi-azure-nextgen#49]
Various parameters have changed between pulumi-azure and azure-nextgen:
pulumi-azure: ip_configurations
publicIpAddressId
subnet_id

azure-nextgen: ip_configurations
publicI**P**Address
subnet

Applies to BastionHost, VirtualNetworkGateway, Azure Firewall (including management_ip_configuration),

Argument classes reduce the differences somewhat between the two providers:

pulumi-azure: ...IpConfigurationArgs
public_ip_address_id
subnet_id

azure-nextgen: ...I**P**ConfigurationArgs
public_ip_address
subnet

**Comment by mikhailshilkov** [comment]
Even more worrying, the docs say it's `public_ip_address` while the dictionary expects `publicIPAddress`

<img width="765" alt="image" src="https://user-images.githubusercontent.com/1454008/95189018-95ed9e80-07cd-11eb-8045-5cd37357d315.png">

**Comment by justinvp** [comment]
> Even more worrying, the docs say it's `public_ip_address` while the dictionary expects `publicIPAddress`

For Python, we need the schema to include `usesIOClasses`. Then the generated docs for the next release of the provider will prefer the input classes, rather than untyped dicts, where the argument is `public_ip_address`.

**Comment by mikhailshilkov** [comment]
@justinvp That's good to know. However, why does the difference in the dictionary property name exist? Why isn't it snake_case for (what it seems like) all properties with "IP" in the name?

**Comment by justinvp** [comment]
Generally, you should be able to use the snake_case name as the dictionary key, and it will get mapped to the camelCase name.

However, in this case, there must be some sort of conflict with a name elsewhere because `public_ip_address` is being mapped to `publicIpAddress`, which isn't correct for this property.

https://github.com/pulumi/pulumi-azure-nextgen/blob/82103a1f566775be94c7ba48e0caa18c77510746/sdk/python/pulumi_azure_nextgen/_tables.py#L4691

I am not sure why some of these have `IP` and other are `Ip`.

**Comment by mikhailshilkov** [comment]
> I am not sure why some of these have IP and other are Ip.

That's how Open API specs define them: [publicIpAddress](https://github.com/Azure/azure-rest-api-specs/blob/6875a9b03dee2a4350866f660c38a7fff3d3ed7e/specification/network/resource-manager/Microsoft.Network/stable/2020-06-01/networkVirtualAppliance.json#L890), [publicIPAddress](https://github.com/Azure/azure-rest-api-specs/blob/6875a9b03dee2a4350866f660c38a7fff3d3ed7e/specification/network/resource-manager/Microsoft.Network/stable/2020-06-01/azureFirewall.json#L400). Both in the same API version, just different resources.

**Comment by justinvp** [comment]
And the problem is the mapping tables are global, so its fundamentally broken here. We really need to address this, sooner than later: https://github.com/pulumi/pulumi/issues/3151

**Comment by justinvp** [comment]
Which, I should say, is one of the reasons why the use of the input classes is preferable: because the snake_case arguments will always map back to the correct underlying Pulumi name. But we need to address this for top-level properties as well.

**Comment by jamesianberry** [comment]
I've managed to overcome the differences throughout my examples using argument classes and this:
```
        # wait for the private ip address of the firewall to become available
        hub_fw_ip = hub_fw.ip_configurations.apply(
-            lambda ipc: ipc[0].get('privateIPAddress')
-            lambda ipc: ipc[0].get('private_ip_address')
+            lambda ipc: ipc[0].private_ip_address
        )
```
The first replaced lambda was from azure-nextgen and the second from azure - the new lambda works for both.

The only exception was where input classes weren't available:
```
       additional_properties = {
            "Network.SNAT.PrivateRanges": private_ranges,
       },
```
This is a parameter on Azure Firewall in azure-nextgen and there was no corresponding parameter in azure.

**Comment by mikhailshilkov** [comment]
There isn't much we can do in this repo, let's track in https://github.com/pulumi/pulumi/issues/3151
