### ISSUE TITLE
Apply auto-naming

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure-nextgen#5]
Currently, name properties are required parameters for every resource and have to be specified explicitly. This is a notable user experience change (and often, not a great one).

Essentially, the same name is written three times, which is awkward:

```ts
const serverGroup = new azure.resources.latest.ResourceGroup("serverGroup", {
    resourceGroupName: "serverGroup",
    location: location,
});
```

We should make names optional in the SDKs and use the auto-populated name if no explicit value is specified.

Things to consider:

1. "Name" properties aren't actually called `name` most of the time, as `resourceGroupName` in the above example. They are always the key property of the resource, being part of its ID.

2. There could be at least two styles of auto-naming: (A) simple copying of the logical name or (B) appending an auto-generated unique suffix (as the previous provider does). We definitely want (A) and most likely (B) - but maybe with a way to configure switching between them, and potentially configure the auto-naming strategy.

**Comment by alastairs** [comment]
I attempted a workaround for (B) in the issue description by generating 8 characters of randomness from a UUID. Unfortunately that is generated on every run, meaning the resource names change on every operation :( Is there a quick hack I can put in place to save the generated names between runs?

**Comment by mikhailshilkov** [comment]
@alastairs You should use `pulumi-random` provider, see an example here: https://github.com/pulumi/examples/blob/master/azure-nextgen-ts-appservice-docker/index.ts#L47

**Comment by alastairs** [comment]
Thanks @mikhailshilkov 👍  It looks like that example uses a single `RandomString` resource. Does each access of `result` create a new random string, or is it desired in that example that every resource have the same random suffix?

**Comment by mikhailshilkov** [comment]
> Does each access of result create a new random string

A single `RandomString` resource produces a stable random value. No matter how many times you use it, it will be the same string, also across multiple runs. A new stack would get a new random value though (basically, the value is generated once and then stored in the stack state).

If you need distinct suffixes, you'd need to have N random resources. 

> is it desired in that example that every resource have the same random suffix?

It doesn't matter for that example. You should judge what works best for your scenario.

**Comment by alastairs** [comment]
Great, thanks for the clarification 👍

**Comment by jamesianberry** [comment]
I have just worked around the lack of auto-naming in [Only essential differences between azure-py-vdc and azureng-py-vdc](https://github.com/pulumi/examples/pull/810/files) and am fairly happy with the result. I would like to be able to pass the name to a resource once, though.

If auto-naming is implemented, it shouldn't be applied to every resource but only those that can result in a potential conflict if multiple stacks are set up in the same subscription, say. For example, routes are scoped to the route table and must be unique on address prefix and priority, so enforcing a unique name doesn't prevent conflicts. Similarly, subnet names are scoped to the virtual network, so there is no problem having the same name in another vnet - but they must have unique address prefixes. So in these cases appending a random blob to the names doesn't achieve anything except to reduce room for expression.

**Comment by darnmason** [comment]
How does this affect updating a resource that needs to be recreated? In the docs it says to use specific names with caution and to specify delete before create so you get the expected behaviour.

With the NextGen project there's no auto naming, which means we're always specifying an exact name. Does this mean Pulumi will always delete before create in this case?

**Comment by mikhailshilkov** [comment]
> Does this mean Pulumi will always delete before create in this case?

Yes, this is correct.

**Comment by mikhailshilkov** [comment]
Here is an example of how to apply basic auto-naming with stack transformations: https://github.com/matwilko/Pulumi.AzureNextGen.Ambient

**Comment by matwilko** [comment]
😊 Thanks for the shout-out - but obviously I'd much prefer an official way to do auto-naming than the hacky reflection stuff I'm having to do in the package, and given resources have various naming conventions for their name property, it's difficult to write reliable logic that catches all resources.

**Comment by mikhailshilkov** [comment]
Indeed, there are some complications, but I have a prototype that seems to be working - I'll try to bring it over the line.

**Comment by mikhailshilkov** [comment]
Resolved in 0.7.0:

Auto-naming is applied for properties that are the last path parameters in their API endpoint path.

There is a twist compared to the normal Pulumi auto-naming:

- For top-level resources (e.g., resource groups, virtual networks, AKS), we append the same random suffix as in pulumi-azure.
- For child resources (e.g., subnets, databases, app slots), we simply copy the logical name to the physical name without any randomization.

Example:

```ts
const resourceGroup = new resources.ResourceGroup("rg");
// the actual resource would be named e.g. "rg8a43bc22"

const blob = new storage.Blob("wwwroot", {
    resourceGroupName: resourceGroup.name,
    accountName: storageAccount.name,
    containerName: storageContainer.name,
    source: new pulumi.asset.FileArchive("wwwroot"),
});
// blob name is simply "wwwroot"
```

**Comment by shawnjones253** [comment]
@mikhailshilkov any rough idea when 0.7 will be released?

**Comment by mikhailshilkov** [comment]
This coming Tuesday. It's going to be a bigger change - watch out for a blog post.
