### ISSUE TITLE
Virtual Network Gateway requires SKU name and tier to be the same

### ISSUE THREAD

**Issue by jamesianberry** [pulumi/pulumi-azure-nextgen#50]
Even though sku name and tier must have the same values, both are required:
        sku = network.VirtualNetworkGatewaySkuArgs(
            name = 'VpnGw1',
            tier = 'VpnGw1',
        ) 
or for an ExpressRoute gateway:
        sku = {
            'name': 'Standard',
            'tier': 'Standard',
        },

Otherwise Azure registers the following error:
Virtual network gateway Sku specified is not valid for gateway /subscriptions/subscription/resourceGroups/rg/providers/Microsoft.Network/virtualNetworkGateway

**Comment by mikhailshilkov** [comment]
This looks to be correctly mapped from the Open API specs. Example:

- [Spec](https://github.com/Azure/azure-rest-api-specs/blob/27cc07ddd294d98e05cb301e07a72378df9f87e8/specification/network/resource-manager/Microsoft.Network/stable/2020-06-01/virtualNetworkGateway.json#L2557-L2619)
- [Sample request](https://github.com/Azure/azure-rest-api-specs/blob/27cc07ddd294d98e05cb301e07a72378df9f87e8/specification/network/resource-manager/Microsoft.Network/stable/2020-06-01/examples/VirtualNetworkGatewayUpdate.json#L28-L31)

**Comment by jamesianberry** [comment]
Fair enough
