### ISSUE TITLE
Error Obtaining a token from the Azure CLI (China only)

### ISSUE THREAD

**Issue by nunodantas** [pulumi/pulumi-azure-nextgen#53]
When running pulumi up using Azure China cloud i get the fallowing error:

error: Preview failed: building authorizer: Error obtaining Authorization Token from the Azure CLI: Error parsing json result from the Azure CLI: Error waiting for the Azure CLI: exit status 1

In debug mode i get this: 

debug: 2020/10/07 10:27:38 Testing if Service Principal / Client Certificate is applicable for Authentication..
    debug: 2020/10/07 10:27:38 Testing if Multi Tenant Service Principal / Client Secret is applicable for Authentication..
    debug: 2020/10/07 10:27:38 Testing if Service Principal / Client Secret is applicable for Authentication..
    debug: 2020/10/07 10:27:38 Testing if Managed Service Identity is applicable for Authentication..
    debug: 2020/10/07 10:27:38 Testing if Obtaining a token from the Azure CLI is applicable for Authentication..
    debug: 2020/10/07 10:27:38 Using Obtaining a token from the Azure CLI for Authentication
    debug: Resource "https://storage.azure.com/" isn't a management domain
    debug: Resource "https://management.core.windows.net/" isn't for the correct Tenant
    debug: 2020/10/07 10:27:38 Getting OAuth config for endpoint https://login.microsoftonline.com/ with  tenant  (*****tenant id**** )

Everything works well in Public Azure with the same account/CLI. With the former Azure provider both Azure China and Public Azure works.

**Comment by nunodantas** [comment]
Tested with a Service Principal, same behavior!

**Comment by viveklak** [comment]
@nunodantas We believe this is now fixed with 0.2.6. Could you check and reopen if this issue still persists?

**Comment by nunodantas** [comment]
Bad news, the issue still persist! i've checked the plugin version and is 0.2.6 .

**Comment by mikhailshilkov** [comment]
Are the URLs in the debug log all the same?

**Comment by nunodantas** [comment]
Yes: 

    debug: Resource "https://management.core.windows.net/" isn't for the correct Tenant
    debug: Resource "https://management.core.windows.net/" isn't for the correct Tenant
    debug: Resource "https://graph.windows.net/" isn't a management domain
    debug: Resource "https://storage.azure.com/" isn't a management domain
    debug: Resource "https://management.azure.com/" isn't for the correct Tenant
    debug: 2020/11/16 21:13:13 Getting OAuth config for endpoint https://login.microsoftonline.com/ with  tenant  ( tenant id )

**Comment by mikhailshilkov** [comment]
Could you try setting `ARM_ENVIRONMENT` env variable to `china` or running `pulumi config set azure-nextgen:environment china` and then try again?

**Comment by nunodantas** [comment]
Apparently i'm still using an old plugin! I've created a new empty stack but i get the following error after delete older plugins. Is there a way to force the newer one?

pulumi:providers:azure-nextgen (default_0_2_1):
    error: no resource plugin 'azure-nextgen-v0.2.1' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource azure-nextgen v0.2.1`

**Comment by mikhailshilkov** [comment]
This is surprising for an empty stack... I would guess you still reference the old version somewhere. Which language runtime are you using and what does your package reference look like?

Also, try with a brand-new project?

**Comment by nunodantas** [comment]
oh...it's working :)
had to install/upgrade python pip pulumi-azure-nextgen package. 
Thanks for all
