### ISSUE TITLE
KeyVault entities management not supported

### ISSUE THREAD

**Issue by orteme** [pulumi/pulumi-azure-nextgen#54]
There is no way at this moment to manage KeyVault entities using Azure NextGen Provider.
Entities:
- [x] Key
- [x] Secret
- [ ] Certificate
- [ ] Access Policy (as a separate resource)

Terraform-based Azure provider has support of these entities:
https://www.pulumi.com/docs/reference/pkg/azure/keyvault/

**Comment by mikhailshilkov** [comment]
Adding Access Policies to the list

**Comment by mikhailshilkov** [comment]
Key Vault secret and key resources are released as part of 0.3.0

**Comment by MisinformedDNA** [comment]
@mikhailshilkov  The [documentation](https://www.pulumi.com/docs/reference/pkg/azure-nextgen/keyvault/vault/#create-a-new-vault-or-update-an-existing-vault) doesn't compile with 0.3.0. Adding

```csharp
Keys =
{
    "encrypt",
},
```

results in 

> cannot convert from 'string' to 'Pulumi.Input<Pulumi.Union<string, Pulumi.AzureNextGen.KeyVault.Latest.KeyPermissions>>'

Is `Union` a new type?

**Comment by mikhailshilkov** [comment]
@MisinformedDNA Good catch. `Union` is not new but its usage here as an enum-like type is new.

As a workaround, you should be able to do 

```cs
Keys =
{
    (Union<string, KeyPermissions>)"encrypt"
}

Could you please file a separate issue to track an improvement to this?

**Comment by andrewdmoreno** [comment]
@mikhailshilkov Was experimenting with these new types to see if I can consolidate usage to Azure NextGen provider for vaults and secrets provisioning. I performed a preview and it indicated it was going to delete the existing Secret on the Azure provider and create it in the new provider. This sounds right conceptually but deleting secrets would trigger the Soft Delete feature of Key Vault and I imagine the subsequent create will fail. 

Was thinking of deleting the existing Secret in the Azure provider from pulumi state and then proceeding with the preview/update. Does this sound like a proper sequence of steps?

**Comment by mikhailshilkov** [comment]
@andrewdmoreno You should first delete the secret from the state (`pulumi state delete <id>`), remove the old code, add new code with `import: <id>` option, and then run `pulumi up`. Then you can remove the `import` option.

**Comment by andrewdmoreno** [comment]
Thank you. I will give that a go.

**Comment by andrewdmoreno** [comment]
@mikhailshilkov I tried the above and I'm not sure what I am getting is the expected behavior. I deleted the secret from state without issue, however, when I try to use the new code with `import: <id>` as suggested I get a warning:

`azure-nextgen:keyvault/latest:Secret (secrets:cosmos-conn-string):
    warning: inputs to import do not match the existing resource; importing this resource will fail`

Here is the code I am running:

```` c#
            // prior code removed for brevity
var cosmosConnectionString = account.Name.Apply(name => Output.Create(GetCosmosConnectionString(_resourceGroupName!, name)));

new Secret("secrets:cosmos-conn-string", 
    new SecretArgs
            {
                SecretName = "CosmosConnectionString",
                VaultName = vault.Name,
                ResourceGroupName = _resourceGroup,
                Properties = new SecretPropertiesArgs
                {
                    Value = cosmosConnectionString,
                    Attributes = new SecretAttributesArgs
                    {
                        Enabled = true
                    }
                }
            }, 
    new CustomResourceOptions
            {
                ImportId = _config.Require("cosmos-conn-string-import-id")
            });
````

The interesting part is that when I look at details it states that I am adding the value of the secret. 

      ~ properties: {
          + value: "AccountEndpoint=<redacted>/;AccountKey=<redacted>"
        }

If I comment out the setting of the `Value`, the preview command runs without warnings. I know for certain that the existing secret in key vault has it's value set to the expected value. Is this expected?

**Comment by mikhailshilkov** [comment]
@andrewdmoreno That's interesting. Could you open a separate issue to track this?

For now, you should be able to work around it by a) Leave the `value` in your code b) Add `IgnoreChanges = { "properties.value" }` c) Import.

**Comment by MisinformedDNA** [comment]
[Use simpler types](https://github.com/pulumi/pulumi-dotnet/issues/43)

**Comment by mikhailshilkov** [comment]
I'll close this issue in favor of https://github.com/pulumi/pulumi-azure-nextgen/issues/267 which is more focused on access policies
