### ISSUE TITLE
Unable to create an empty logic app workflow

### ISSUE THREAD

**Issue by alan0609** [pulumi/pulumi-azure-nextgen#56]
In the old Azure provider I could create an empty Workflow using

`new Pulumi.Azure.LogicApps.Workflow(name, new WorkflowArgs
{
    Name = <name>,
    ResourceGroupName = <rgname>
});`

If I try a similar thing with nextgen 

`new Pulumi.AzureNextGen.Logic.Latest.Workflow(laSettings.Name, new Pulumi.AzureNextGen.Logic.Latest.WorkflowArgs
{
    WorkflowName = <name>,
    ResourceGroupName = <rgname>
});`

It fails with an error 

`error: Code="InvalidWorkflow" Message="The provided workflow definition is not valid."`

Even though the Definition property is specified as optional in the [documentation](https://www.pulumi.com/docs/reference/pkg/azure-nextgen/logic/workflow/)

**Comment by mikhailshilkov** [comment]
The existing `pulumi-azure` provider actually bootstraps an empty definition behind the scenes, so an equivalent resource in the new `pulumi-azure-nextgen` would be:

``` cs
new Pulumi.AzureNextGen.Logic.Latest.Workflow("workflow", new Pulumi.AzureNextGen.Logic.Latest.WorkflowArgs
{
    WorkflowName = "mywf",
    ResourceGroupName = resourceGroup.Name,
    Location = resourceGroup.Location,
    Definition = new Dictionary<string, object>
    {
        {"$schema", "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#"},
        {"contentVersion", "1.0.0.0"},
        {"actions", ImmutableDictionary<string, string>.Empty },
        {"triggers", ImmutableDictionary<string, string>.Empty },
    }.ToImmutableDictionary()
});
```

However, this doesn't seem to work either right now - I opened #58 to track.

**Comment by mikhailshilkov** [comment]
I'll close this issue for now. Please do let me know if you still have an open question.

**Comment by alan0609** [comment]
Thnaks @mikhailshilkov, that seems to be working now!
