### ISSUE TITLE
Unable to add key-value and labels to AppConfiguration service

### ISSUE THREAD

**Issue by william-liebenberg** [pulumi/pulumi-azure-nextgen#62]
Hi all

I'm trying to use the Azure AppConfiguration Service, but I am limited to just creating the service and unable to add any key-value+labels to it. Can't find anything in the pulumi docs on how to do this.

Here is the docs and sample ARM template: [https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-resource-manager](https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-resource-manager)

I'm not sure which API version `AppConfiguration.Latest` actually is, but the most recent dated namespace is `2020-06-01`. The ARM examples above is using the `2020-07-01-preview` API...

Am I looking in the wrong place or is it simply not available in Pulumi yet?

Thanks

**Comment by mikhailshilkov** [comment]
The latest version points to `2020-06-01` indeed but it has [no `keyValues` endpoints](https://github.com/Azure/azure-rest-api-specs/blob/01ed36c1d67661713d805d743cf5e6197f4c6c18/specification/appconfiguration/resource-manager/Microsoft.AppConfiguration/stable/2020-06-01/appconfiguration.json).

I [raised an issue](https://github.com/Azure/azure-rest-api-specs/issues/11136) on the Open API spec repo to publish `2020-07-01-preview`.

**Comment by mikhailshilkov** [comment]
The `V20200701Preview` API is now available in the latest alpha builds (starting with https://www.nuget.org/packages/Pulumi.AzureNextGen/0.2.4-alpha.1603716639) and will be included in 0.2.4 (or 0.3.0, whatever the next release is).

**Comment by william-liebenberg** [comment]
Thanks for that @mikhailshilkov 

I'll try it out soon
👍
