### ISSUE TITLE
Unable to install azurenextgen plugin for Windows

### ISSUE THREAD

**Issue by orteme** [pulumi/pulumi-azure-nextgen#70]
### Issue description
Staring today 10/16/2020 I am unable to install azurenextgen plugin anymore.
`pulumi plugin install ` or `pulumi plugin install resource azurenextgen 0.2.2` fails with error HTTP 403
```
>pulumi plugin install resource azurenextgen 0.2.2
[resource plugin azurenextgen-0.2.2] installing
error: [resource plugin azurenextgen-0.2.2] downloading from : 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-azurenextgen-v0.2.2-windows-amd64.tar.gz
```
The same behavior with other plugin versions:
 - 0.2.1
 - 0.2.0
 - 0.1.0

### Steps to reproduce
1. Install Pulumi CLI v2.12.0 for Windows
2. Run `pulumi plugin install resource azurenextgen 0.2.2`

**Comment by mikhailshilkov** [comment]
Try `azure-nextgen` with a dash

**Comment by tusharshahrs** [comment]
I can replicate the behavior with:
 $ `pulumi plugin install`
running 'dotnet build -nologo .'
  Determining projects to restore...
  All projects are up-to-date for restore.
  temp3temp3 -> ../temp3/bin/Debug/netcoreapp3.1/temp3temp3.dll
Build succeeded.
    0 Warning(s)
    0 Error(s)
Time Elapsed 00:00:00.84
'dotnet build -nologo .' completed successfully
[resource plugin azurenextgen-0.2.2] installing
```error: [resource plugin azurenextgen-0.2.2] downloading from : 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-azurenextgen-v0.2.2-darwin-amd64.tar.g```

When I run 
 $ `pulumi plugin install resource azure-nextgen 0.2.2`
```[resource plugin azure-nextgen-0.2.2] installing```

**Comment by mikhailshilkov** [comment]
@tusharshahrs Thanks for the repro, I can also see this now. It looks like our .NET plugin discovery is broken here.

**Comment by jaxxstorm** [comment]
@tusharshahrs can you also include the pulumi program you used to repro?

**Comment by tusharshahrs** [comment]
@jaxxstorm Here you go:

$ `mkdir ~/temp/temp4`
$ `cd ~/temp/temp4`
$ `pulumi new azure-nextgen-csharp`
 ~/temp/temp4 $ pulumi plugin install resource azure-nextgen 0.2.2
_[resource plugin azure-nextgen-0.2.2] installing_
tusharshah@Tushars-MBP ~/temp/temp4 $ `pulumi plugin install`
_running 'dotnet build -nologo .'
  Determining projects to restore...
  All projects are up-to-date for restore._

  _temp4 -> ...temp/temp4/bin/Debug/netcoreapp3.1/temp4.dll_

_Build succeeded.
    0 Warning(s)
    0 Error(s)
Time Elapsed 00:00:00.80_

_'dotnet build -nologo .' completed successfully
[resource plugin azurenextgen-0.2.2] installing_
_error: [resource plugin azurenextgen-0.2.2] downloading from : **403 HTTP error fetching plugin from** https://get.pulumi.com/releases/plugins/pulumi-resource-azurenextgen-v0.2.2-darwin-amd64.tar.gz_

These are the files that are generated:
MyStack.cs  Program.cs  Pulumi.yaml  bin  obj  temp4.csproj

pulumi version
_v2.12.0_
