### ISSUE TITLE
Add support for F# template

### ISSUE THREAD

**Issue by abhi18av** [pulumi/pulumi-azure-nextgen#73]
Hi Team,

Thanks for the wonderful product!

I was wondering whether the `azure-nextgen` is stable enough to add support for the `F#` template.

As of today, I think the only `C#` is available.

```
$ pulumi new azure-nextgen-fsharp
error: template 'azure-nextgen-fsharp' not found

Did you mean this?
        azure-nextgen-csharp

```

**Comment by mikhailshilkov** [comment]
Yes, we should definitely do this!
