### ISSUE TITLE
[arm2pulumi] Site should specify that it's in beta

### ISSUE THREAD

**Issue by MisinformedDNA** [pulumi/pulumi-azure-nextgen#75]
To avoid customer confusion, https://www.pulumi.com/arm2pulumi/ should have a "Beta" badge on it to let clients know that it is not finished and some errors are expected. Maybe also link to [known issues](https://github.com/pulumi/pulumi-azure-nextgen/issues?q=is%3Aissue+is%3Aopen+label%3Aarm2pulumi).

**Comment by lukehoban** [comment]
My suggestion to address this is that we link to known issues as part of the help text we present when users get a conversion error.  We've improved these conversion errors to be a bit more actionable recently - but adding the GitHub issue list would help guide folks to the right place to both understand where there might be known gaps, and where thy can report any new issues they are seeing.
