### ISSUE TITLE
[arm2pulumi] Converter site has some CSS issues

### ISSUE THREAD

**Issue by MisinformedDNA** [pulumi/pulumi-azure-nextgen#77]
There are a bunch of unusable scroll bars and the left table bleeds out of it's container.

![image](https://user-images.githubusercontent.com/1784452/96473029-c6ceca00-11f6-11eb-82eb-a492f72ab607.png)

This may have something to do with me getting a [new monitor](https://www.amazon.com/Dell-Marketing-Led-Lit-Monitor-U4919DW/dp/B07KMQT7DB/) (running at [3840x1080](https://www.whatsmybrowser.org/b/F3M5Y))

But my laptop is also displaying the issue, which I hadn't noticed before.

That said, if I use the F12 tools, the issue goes away at some resolutions.

**Comment by cnunciato** [comment]
Thanks for the report! @MisinformedDNA would you mind confirming your OS and browser versions for me? Is this Edge on Windows?
