### ISSUE TITLE
SourceControl not available on web app

### ISSUE THREAD

**Issue by DevSecNinja** [pulumi/pulumi-azure-nextgen#79]
I'm trying to configure the source control settings on a Linux web app. My initial thought was that I needed to deploy the WebAppSourceControl resource, but Pulumi will throw an error that the resource already exists. Which is true, because by default Azure will create the /<yourApp>/sourcecontrols/web resource. (Only visible via resources.azure.com)

I see that Terraform allows a `source_control` block on the app service resource itself: https://www.terraform.io/docs/providers/azurerm/r/app_service.html

Any idea how I can configure source control with Pulumi?

Thanks!

**Comment by viveklak** [comment]
Hi @DevSecNinja. I believe this has to do with the sourcecontrol/web resource being a "singleton". If my understanding is correct you might have to import the existing resource and update. I will have to try it out and will update this ticket.

**Comment by DevSecNinja** [comment]
Thanks for the swift reply @viveklak! Hmm, but that means I first have to create the web app, import the WebAppSourceControl and modify it? Seems a bit complicated when comparing it to a `source_control` block.
