### ISSUE TITLE
Configure StorageAccount as a static website and upload website files

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-azure-nextgen#86]
Currently, ARM does not support creating a StorageAccount as a static website, nor does it support uploading files to a blob container. 
Therefore, pulumi-azure-nextgen does not support these capabilities.

However, the classic provider supports these operations as in this example: https://github.com/pulumi/examples/blob/master/azure-ts-static-website/index.ts

So, it would be useful to have these capabilities in the nextgen provider as well.

**Comment by mikhailshilkov** [comment]
Potentially useful observation: there is a WIP `storage-dataplane-preview` branch with Storage Data Plane API  specs: https://github.com/Azure/azure-rest-api-specs/blob/storage-dataplane-preview/specification/storage/data-plane/

**Comment by mikhailshilkov** [comment]
Current workaround is to enable static website features with the Azure Storage SDK. Here is an example in C# (the post describes the "old" terraform-based provider but the same technique is applicable here): https://blog.headforcloud.com/2020/02/09/pulumi-azure-static-sites/

**Comment by mikhailshilkov** [comment]
The `StorageAccountStaticWebsite` resource will be released in 0.6.0
