### ISSUE TITLE
AppConfiguration v20200701preview is not available in the latest nuget.

### ISSUE THREAD

**Issue by Badabum** [pulumi/pulumi-azure-nextgen#89]
AppConfiguration v20200701preview is not available in the latest nuget package(even alpha version). I see there is a generated folder in the repo but still not in the package itself.

**Comment by mikhailshilkov** [comment]
I haven't checked but I think it's in https://www.nuget.org/packages/Pulumi.AzureNextGen/0.2.4-alpha.1603716639

**Comment by Badabum** [comment]
indeed, it is. Strange that it was not present when I first updated. Probably some caching. Thanks @mikhailshilkov
