### ISSUE TITLE
Cannot find package for go

### ISSUE THREAD

**Issue by larsmaes** [pulumi/pulumi-azure-nextgen#9]
❯ go get github.com/pulumi/pulumi-azure-nextgen/sdk/go
go get github.com/pulumi/pulumi-azure-nextgen/sdk/go: module github.com/pulumi/pulumi-azure-nextgen/sdk@upgrade found (v0.1.0), but does not contain package github.com/pulumi/pulumi-azure-nextgen/sdk/go

**Comment by stack72** [comment]
Hi @larsmaes 

You should just need to run `go get github.com/pulumi/pulumi-azure-nextgen/sdk`

Sorry for the confusion here

**Comment by larsmaes** [comment]
Ah.. so simple, thanks!!

**Comment by stack72** [comment]
I will update the README and close this out - apologies again for the wrong info here
