### ISSUE TITLE
autorest/azure: error response cannot be parsed: "" error: EOF

### ISSUE THREAD

**Issue by jkonecki-techfabric** [pulumi/pulumi-azure-nextgen#97]
I'm trying to connect AppService to VNet using the following code:

```
new WebAppVnetConnection($"{options.Tenant}-appServiceVnet-{options.Name}-{options.Environment}", new WebAppVnetConnectionArgs
{
    ResourceGroupName = options.ResourceGroupName,
    Name = "vrm-appService-accessmanagement-dev/9c8e4d83-8cdf-4989-88ca-0703bd27ddcf_appServices",
    VnetName = options.Vnet.NetworkName,
    VnetResourceId = options.Vnet.AppServiceSubnetId,
    IsSwift = true
 });
```

The following change is detected by Pulumi:
```
    + azure-nextgen:web/latest:WebAppVnetConnection: (create)
        [urn=urn:pulumi:dev::VRM::azure-nextgen:web/latest:WebAppVnetConnection::vrm-appServiceVnet-accessmanagement-dev]
        [provider=urn:pulumi:dev::VRM::pulumi:providers:azure-nextgen::default_0_2_3::c477d550-ad95-47c6-8ece-b0984f2979dd]
        isSwift          : true
        name             : "vrm-appService-accessmanagement-dev/9c8e4d83-8cdf-4989-88ca-0703bd27ddcf_appServices"
        resourceGroupName: "vrm-dev"
        vnetName         : "vrm-vnet-dev"
        vnetResourceId   : "/subscriptions/b3ec3959-b60e-47f0-9239-dc13b6ee01fa/resourceGroups/vrm-dev/providers/Microsoft.Network/virtualNetworks/vrm-vnet-dev/subnets/appServices"
```

The updates fails with the the following error:

```
Diagnostics:
  azure-nextgen:web/latest:WebAppVnetConnection (vrm-appServiceVnet-accessmanagement-dev):
    error: cannot check existence of resource /subscriptions/b3ec3959-b60e-47f0-9239-dc13b6ee01fa/resourceGroups/vrm-dev/providers/Microsoft.Web/sites/vrm-appService-accessmanagement-dev%2F9c8e4d83-8cdf-4989-88ca-0703bd27ddcf_appServices/virtualNetworkConnections/vrm-vnet-dev: autorest/azure: error response cannot be parsed: "" error: EOF: autorest/azure: error response cannot be parsed: "" error: EOF
```

Is this caused by URL encoded `/`? `accessmanagement-dev***%2F***9c8e4d83-8cdf-`

What can I do to further investigate this failure?

**Comment by mikhailshilkov** [comment]
I believe the `Name` should not contain slashes, nor should it contain the name of the parent App Service.

**Comment by jkonecki-techfabric** [comment]
Slash is included in the sample ARM templates.
Removing site name and slash results in error:

```
error: Code="ResourceNotFound" Message="The Resource 'Microsoft.Web/sites/9c8e4d83-8cdf-4989-88ca-0703bd27ddcf_appServices' under resource group 'vrm-dev' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"
```

**Comment by mikhailshilkov** [comment]
ARM Templates have different conventions for names. I'm probably wrong and the `Name` should be the name of the App Service then, still without a slash or the second part.

**Comment by jkonecki-techfabric** [comment]
Nope, getting this error:

  azure-nextgen:web/latest:WebAppVnetConnection (vrm-appServiceVnet-accessmanagement-dev):
    error: autorest/azure: Service returned an error. Status=<nil> <nil>

**Comment by viveklak** [comment]
> Nope, getting this error:
> 
> ```
>   azure-nextgen:web/latest:WebAppVnetConnection (vrm-appServiceVnet-accessmanagement-dev):
>     error: autorest/azure: Service returned an error. Status=<nil> <nil>
> ```

Ran into this less-than-useful error message just this morning which we should fix. Could you take a look at eventlogs for the resource group in the meantime (azure console or CLI)? It should provide a hint as to what the actual failure was.

**Comment by jkonecki-techfabric** [comment]
The error is:

Regional VNET Integration network cannot be modified with this API call. Please use call /networkConfig/VirtualNetwork.

**Comment by viveklak** [comment]
Could you post the sample ARM template you are using? FWIW /networkConfig/VirtualNetwork corresponds to `WebAppSwiftVirtualNetworkConnection` so sounds like perhaps the template is using the wrong snippet? 

However, we are tracking an existing issue here which doesn't let you use WebAppSwiftVirtualNetworkConnection at the moment: https://github.com/pulumi/pulumi-azure-nextgen/issues/94

**Comment by jkonecki-techfabric** [comment]
I sucessfully switched to `WebAppSwiftVirtualNetworkConnection`.
